const grade2 = {
  grade: 2,
  roundSize: 10,
  pool: [
    { word: "about",   hint: "On the subject of something",       sentence: "Can you tell me about your day?" },
    { word: "again",   hint: "One more time",                     sentence: "Please say that again — I missed it." },
    { word: "always",  hint: "Every single time",                 sentence: "She always brushes her teeth before bed." },
    { word: "around",  hint: "In a circle or nearby",             sentence: "We walked around the whole park." },
    { word: "because", hint: "Used to give a reason",             sentence: "I wore a coat because it was cold." },
    { word: "before",  hint: "Earlier in time",                   sentence: "Wash your hands before you eat." },
    { word: "bring",   hint: "Carry something to a place",        sentence: "Please bring your book to class." },
    { word: "carry",   hint: "Hold and move something",           sentence: "She could carry two bags at once." },
    { word: "clean",   hint: "Not dirty",                         sentence: "His room is always clean and tidy." },
    { word: "drink",   hint: "Take liquid into your mouth",       sentence: "Remember to drink water every day." },
    { word: "eight",   hint: "The number after seven",            sentence: "There are eight apples in the basket." },
    { word: "every",   hint: "Each one without exception",        sentence: "Every student passed the test." },
    { word: "found",   hint: "Past tense of find",                sentence: "She found her lost pencil under the desk." },
    { word: "funny",   hint: "Makes you laugh",                   sentence: "He told a very funny joke." },
    { word: "green",   hint: "The color of grass",                sentence: "The frog was a bright green color." },
    { word: "jump",    hint: "Spring off the ground",             sentence: "The rabbit can jump really high." },
    { word: "know",    hint: "Have information about",            sentence: "I know all of my multiplication tables." },
    { word: "light",   hint: "Illumination; also not heavy",      sentence: "Turn on the light so I can read." },
    { word: "money",   hint: "Coins and bills you use to buy",    sentence: "He saved his money for a new toy." },
    { word: "never",   hint: "At no time",                        sentence: "I never go to bed without saying prayers." },
    { word: "fast",    hint: "Moving with great speed",           sentence: "The cheetah is a very fast animal." },
    { word: "slow",    hint: "Not moving quickly",                sentence: "A turtle is known for being slow." },
    { word: "tall",    hint: "Having great height",               sentence: "The giraffe is a tall animal." },
    { word: "short",   hint: "Not tall or long",                  sentence: "The pencil became too short to use." },
    { word: "cold",    hint: "Having a low temperature",          sentence: "It is too cold to play outside without a coat." },
    { word: "warm",    hint: "Comfortably hot",                   sentence: "The fire kept us warm in winter." },
    { word: "hard",    hint: "Not soft or easy",                  sentence: "A rock is very hard." },
    { word: "soft",    hint: "Easy to press; not hard",           sentence: "The baby's blanket is soft." },
    { word: "far",     hint: "A long distance away",              sentence: "We had to travel far to see grandma." },
    { word: "near",    hint: "Not far away",                      sentence: "The grocery store is near our house." },
    { word: "part",    hint: "A piece of a whole",                sentence: "I ate only a part of the sandwich." },
    { word: "whole",   hint: "Complete; not broken or divided",   sentence: "He ate the whole pizza by himself." },
    { word: "high",    hint: "Far up in the air",                 sentence: "The kite flew high in the sky." },
    { word: "low",     hint: "Close to the ground",               sentence: "The plane flew very low." },
    { word: "first",   hint: "Number one in order",               sentence: "She won first place in the race." },
    { word: "last",    hint: "Coming after all others",           sentence: "December is the last month of the year." },
    { word: "right",   hint: "Correct; or a direction",           sentence: "You got the right answer!" },
    { word: "left",    hint: "Opposite of right direction",       sentence: "Turn left at the stop sign." },
    { word: "open",    hint: "Not closed",                        sentence: "Please open the window for fresh air." },
    { word: "shut",    hint: "To close",                          sentence: "Make sure you shut the door." },
    { word: "wide",    hint: "Having a large distance across",    sentence: "The river was too wide to cross." },
    { word: "deep",    hint: "Going down a long way",             sentence: "The pool is very deep at this end." },
    { word: "full",    hint: "Containing as much as possible",    sentence: "The cup is full of water." },
    { word: "start",   hint: "To begin something",                sentence: "When does the movie start?" },
    { word: "game",    hint: "An activity you play for fun",      sentence: "We played a fun board game." },
    { word: "home",    hint: "The place where you live",          sentence: "I cannot wait to go home." },
    { word: "time",    hint: "Measured in hours and minutes",     sentence: "What time is it right now?" },
    { word: "room",    hint: "A space inside a house",            sentence: "We painted my bedroom." },
    { word: "door",    hint: "You open it to enter a room",       sentence: "He knocked on the front door." },
    { word: "love",     hint: "A strong feeling of affection",     sentence: "I love my family very much." },
    { word: "also",     hint: "In addition; too",                sentence: "She also likes to sing." },
    { word: "animal",   hint: "A living creature",               sentence: "A horse is a large animal." },
    { word: "branch",   hint: "An arm of a tree",                sentence: "The bird sat on a low branch." },
    { word: "bread",    hint: "Baked food made from flour",      sentence: "We made fresh bread at home." },
    { word: "brown",    hint: "The color of wood or earth",      sentence: "The puppy has brown fur." },
    { word: "camel",    hint: "A desert animal with humps",      sentence: "The camel walked across the hot sand." },
    { word: "chase",    hint: "To run after something",          sentence: "The dog likes to chase its tail." },
    { word: "check",    hint: "To examine or inspect",           sentence: "Please check your work before handing it in." },
    { word: "cherry",   hint: "A small red fruit",               sentence: "She put a cherry on top of the cake." },
    { word: "child",    hint: "A young person",                  sentence: "Every child deserves a great education." },
    { word: "class",    hint: "A group of students together",    sentence: "Our class went on a field trip." },
    { word: "clown",    hint: "A performer who makes people laugh", sentence: "The clown at the birthday party was funny." },
    { word: "coast",    hint: "Land near the ocean",             sentence: "We drove along the coast all day." },
    { word: "comet",    hint: "A space object with a bright tail", sentence: "Everyone went outside to see the comet." },
    { word: "common",   hint: "Happening often; shared",         sentence: "Colds are very common in winter." },
    { word: "corner",   hint: "The place where two sides meet",  sentence: "She waited at the street corner." },
    { word: "cotton",   hint: "A soft, natural fabric",          sentence: "My shirt is made from soft cotton." },
    { word: "count",    hint: "To say numbers in order",         sentence: "Count to twenty before you open your eyes." },
    { word: "crowd",    hint: "A large group of people",         sentence: "A big crowd gathered in the park." },
    { word: "daisy",    hint: "A common white flower",           sentence: "She picked a yellow daisy from the garden." },
    { word: "damp",     hint: "Slightly wet",                    sentence: "The grass was damp after the rain." },
    { word: "dance",    hint: "Move rhythmically to music",      sentence: "She loves to dance at every party." },
    { word: "dream",    hint: "Images seen while sleeping",      sentence: "I had a wonderful dream last night." },
    { word: "dress",    hint: "A piece of clothing for girls",   sentence: "She wore a beautiful white dress." },
    { word: "earth",    hint: "Our planet; also soil",           sentence: "We need to take care of the Earth." },
    { word: "elbow",    hint: "The joint in the middle of your arm", sentence: "He scraped his elbow when he fell." },
    { word: "empty",    hint: "Containing nothing",              sentence: "The glass is completely empty." },
    { word: "fence",    hint: "A barrier around a yard",         sentence: "The dog jumped over the fence." },
    { word: "field",    hint: "A large open area of land",       sentence: "The horses ran freely across the field." },
    { word: "flame",    hint: "The visible part of a fire",      sentence: "The candle flame flickered in the wind." },
    { word: "float",    hint: "To rest on top of water",         sentence: "Leaves float gently on the pond." },
    { word: "flower",   hint: "The colorful part of a plant",    sentence: "She planted a flower in the garden." },
    { word: "forest",   hint: "A large area covered with trees", sentence: "We hiked through the dark forest." },
    { word: "fresh",    hint: "Not old or spoiled",              sentence: "I love the smell of fresh bread." },
    { word: "friend",   hint: "A person you like and trust",     sentence: "My best friend makes me laugh every day." },
    { word: "fruit",    hint: "A sweet food that grows on trees",sentence: "An apple is a type of fruit." },
    { word: "glove",    hint: "Worn on your hand to keep warm",  sentence: "She lost her glove in the snow." },
    { word: "grain",    hint: "A small hard seed",               sentence: "Rice is a type of grain." },
    { word: "grape",    hint: "A small round fruit",             sentence: "She ate a bunch of grapes." },
    { word: "grass",    hint: "The green plants that cover lawns", sentence: "We played on the cool, soft grass." },
    { word: "group",    hint: "A number of things or people together", sentence: "A group of students worked together." },
    { word: "happy",    hint: "Feeling great pleasure",          sentence: "I am so happy to see you!" },
    { word: "honey",    hint: "Sweet golden liquid made by bees",sentence: "She put honey in her tea." },
    { word: "horse",    hint: "A large animal people ride",      sentence: "The horse galloped across the meadow." },
    { word: "house",    hint: "A building where people live",    sentence: "Our house has a big backyard." },
    { word: "island",   hint: "Land surrounded by water",        sentence: "We took a boat to the island." },
    { word: "jacket",   hint: "A short coat",                    sentence: "Remember to bring your jacket." },
    { word: "jungle",   hint: "A wild forest with many animals", sentence: "Lions live in the jungle." },
    { word: "kettle",   hint: "A pot used to boil water",        sentence: "The kettle began to whistle." },
  ],
};
export default grade2;
