const grade7 = {
  grade: 7, roundSize: 14,
  pool: [
    { word: "aberration",       hint: "A departure from what is normal",            sentence: "His rude comment was an aberration — he is usually very kind." },
    { word: "acquiesce",        hint: "Accept something reluctantly but without protest", sentence: "She chose to acquiesce rather than argue further." },
    { word: "ambivalence",      hint: "Having mixed feelings about something",       sentence: "His ambivalence about the move made it hard to pack." },
    { word: "anachronism",      hint: "Something out of its proper time period",     sentence: "A knight using a smartphone would be a clear anachronism." },
    { word: "cacophony",        hint: "A harsh, discordant mixture of sounds",       sentence: "The cafeteria was filled with a cacophony of voices." },
    { word: "consternation",    hint: "Feelings of anxiety or dismay",               sentence: "The sudden change in plans caused great consternation." },
    { word: "corroborate",      hint: "Confirm or support with evidence",            sentence: "The second witness helped corroborate his story." },
    { word: "denounce",         hint: "Publicly declare to be wrong or evil",        sentence: "The community gathered to denounce the injustice." },
    { word: "desolate",         hint: "Deserted; lacking inhabitants; bleak",        sentence: "After the storm, the streets were completely desolate." },
    { word: "ephemeral",        hint: "Lasting for a very short time",               sentence: "Beauty is ephemeral, but character lasts forever." },
    { word: "exacerbate",       hint: "Make a problem or situation worse",           sentence: "Arguing only served to exacerbate the misunderstanding." },
    { word: "fortitude",        hint: "Courage in pain or adversity",                sentence: "She faced her illness with remarkable fortitude." },
    { word: "gregarious",       hint: "Fond of company; sociable",                   sentence: "He was gregarious by nature and knew everyone by name." },
    { word: "hypocritical",     hint: "Claiming beliefs one does not have",          sentence: "It is hypocritical to preach honesty while telling lies." },
    { word: "inconsequential",  hint: "Not important or significant",                sentence: "He dismissed the error as inconsequential." },
    { word: "nomenclature",     hint: "A system of names used in a field",           sentence: "Scientists use precise nomenclature to avoid confusion." },
    { word: "ostentatious",     hint: "Designed to impress; showy",                  sentence: "The ostentatious mansion was visible from across the lake." },
    { word: "precarious",       hint: "Not securely held; risky",                    sentence: "He held the glass in a precarious grip at the edge of the table." },
    { word: "superfluous",      hint: "Unnecessary; more than enough",               sentence: "The lengthy introduction was superfluous and could be cut." },
    { word: "vacillate",        hint: "Waver between different opinions",            sentence: "Don't vacillate — make a decision and stick with it." },
    { word: "abbreviate",       hint: "Shorten a word, phrase, or text",             sentence: "You can abbreviate 'Doctor' to 'Dr.' when writing titles." },
    { word: "accelerate",       hint: "Begin to move more quickly",                  sentence: "The car started to accelerate as it entered the highway." },
    { word: "acceptable",       hint: "Able to be agreed on; suitable",              sentence: "Her essay was of an acceptable standard." },
    { word: "accompany",        hint: "Go somewhere with as a companion",            sentence: "Would you like to accompany me to the concert?" },
    { word: "accumulate",       hint: "Gather together or acquire an increasing number", sentence: "Dust tends to accumulate under the beds." },
    { word: "accustomed",       hint: "Customary or usual",                          sentence: "He quickly became accustomed to the new daily routine." },
    { word: "achiever",         hint: "A person who attains a high level of success",sentence: "She has always been a high achiever in academics." },
    { word: "acclimate",        hint: "Become accustomed to a new climate",          sentence: "It takes a few days to acclimate to higher altitudes." },
    { word: "acoustics",        hint: "The properties or qualities of a room for sound", sentence: "The auditorium has excellent acoustics for musical performances." },
    { word: "acquaintance",     hint: "A person's knowledge or experience of something", sentence: "He is merely a casual acquaintance, not a close friend." },
    { word: "adequate",         hint: "Satisfactory or acceptable in quality or quantity", sentence: "Ensure you have adequate water for the long hike." },
    { word: "adolescent",       hint: "In the process of developing from a child into an adult", sentence: "The adolescent years can be full of rapid changes." },
    { word: "advantageous",     hint: "Involving or creating favorable circumstances", sentence: "It is advantageous to start studying a week before the exam." },
    { word: "aggravate",        hint: "Make a problem, injury, or offense worse",    sentence: "Scratching the bug bite will only aggravate the itch." },
    { word: "agile",            hint: "Able to move quickly and easily",             sentence: "The monkey was very agile climbing through the trees." },
    { word: "allegiance",       hint: "Loyalty or commitment of a subordinate",      sentence: "We pledge allegiance to the flag every morning." },
    { word: "alliance",         hint: "A union or association formed for mutual benefit", sentence: "The three countries formed a strong military alliance." },
    { word: "allocate",         hint: "Distribute resources or duties for a particular purpose", sentence: "The manager will allocate tasks to the team tomorrow." },
    { word: "almanac",          hint: "An annual calendar containing important dates", sentence: "The farmer checked the almanac for weather predictions." },
    { word: "ammunition",       hint: "A supply or quantity of bullets and shells",  sentence: "They ran out of ammunition during the intense paintball game." },
    { word: "analyze",          hint: "Examine methodically and in detail",          sentence: "We need to analyze the data before drawing any conclusions." },
    { word: "anecdote",         hint: "A short, amusing story about a real incident",sentence: "The speaker opened his presentation with a funny anecdote." },
    { word: "anguish",          hint: "Severe mental or physical pain or suffering", sentence: "She cried out in anguish when she stubbed her toe." },
    { word: "anniversary",      hint: "The date an event took place in a previous year", sentence: "My parents are celebrating their twentieth wedding anniversary." },
    { word: "anonymous",        hint: "Of unknown name",                             sentence: "The tip to the police was completely anonymous." },
    { word: "anticipate",       hint: "Regard as probable; expect or predict",       sentence: "We anticipate a large crowd for the championship game." },
    { word: "apology",          hint: "A regretful acknowledgment of an offense",    sentence: "He issued a sincere apology for his mistake." },
    { word: "apparatus",        hint: "Technical equipment or machinery needed",     sentence: "The gym is equipped with all the latest exercise apparatus." },
    { word: "appease",          hint: "Pacify or placate someone",                   sentence: "They tried to appease the crying baby with a toy." },
    { word: "appreciate",       hint: "Recognize the full worth of",                 sentence: "I appreciate your help with this difficult task." },
  ],
};
export default grade7;
