const grade1 = {
  grade: 1,
  roundSize: 8,
  pool: [
    { word: "the",  hint: "Most common word in English",     sentence: "The dog ran to the park." },
    { word: "and",  hint: "Connects two things together",    sentence: "I have a cat and a dog." },
    { word: "cat",  hint: "A furry pet that meows",          sentence: "The cat sat on the mat." },
    { word: "dog",  hint: "A furry pet that barks",          sentence: "My dog likes to play fetch." },
    { word: "big",  hint: "The opposite of small",           sentence: "That is a big red ball." },
    { word: "run",  hint: "Faster than walking",             sentence: "I run to school every day." },
    { word: "sun",  hint: "Lights up the daytime sky",       sentence: "The sun is bright today." },
    { word: "fun",  hint: "Means enjoyable",                 sentence: "We had so much fun at the park." },
    { word: "bat",  hint: "You use it in baseball",          sentence: "He hit the ball with his bat." },
    { word: "hat",  hint: "Worn on your head",               sentence: "She wore a red hat to the party." },
    { word: "mat",  hint: "You wipe your feet on it",        sentence: "Please wipe your feet on the mat." },
    { word: "sit",  hint: "What you do in a chair",          sentence: "Please sit down in your seat." },
    { word: "hot",  hint: "The opposite of cold",            sentence: "Be careful — the soup is very hot." },
    { word: "wet",  hint: "The opposite of dry",             sentence: "My shoes got wet in the rain." },
    { word: "red",  hint: "The color of an apple",           sentence: "She wore a beautiful red dress." },
    { word: "bed",  hint: "You sleep in it at night",        sentence: "I make my bed every morning." },
    { word: "boy",  hint: "A male child",                    sentence: "The young boy rode his bike." },
    { word: "girl", hint: "A female child",                  sentence: "The little girl wore a pink dress." },
    { word: "toy",  hint: "Something you play with",         sentence: "He shared his favorite toy with his brother." },
    { word: "man",  hint: "An adult male person",            sentence: "The tall man reached the top shelf." },
    { word: "play", hint: "To have fun doing something",     sentence: "We like to play games after dinner." },
    { word: "day",  hint: "When the sun is up",              sentence: "It is a beautiful sunny day." },
    { word: "say",  hint: "To speak words",                  sentence: "What did you say to me?" },
    { word: "may",  hint: "Asking for permission",           sentence: "May I please have a cookie?" },
    { word: "way",  hint: "A path or direction",             sentence: "Which way to the playground?" },
    { word: "see",  hint: "To look with your eyes",          sentence: "I can see the bird in the tree." },
    { word: "tree", hint: "A tall plant with a trunk and leaves", sentence: "The apples fell from the tree." },
    { word: "bee",  hint: "A flying insect that makes honey",sentence: "The bee landed on a flower." },
    { word: "look", hint: "To turn your eyes toward something", sentence: "Look at the stars in the sky!" },
    { word: "book", hint: "Pages with words and pictures to read", sentence: "I read a book before bed." },
    { word: "good", hint: "The opposite of bad",             sentence: "You did a good job on your homework." },
    { word: "foot", hint: "The body part you stand on",      sentence: "He stubbed his toe on his foot." },
    { word: "out",  hint: "The opposite of in",              sentence: "The cat wants to go out." },
    { word: "down", hint: "The opposite of up",              sentence: "Please sit down quietly." },
    { word: "now",  hint: "At this very moment",             sentence: "We need to leave right now." },
    { word: "how",  hint: "Asking the way to do something",  sentence: "How do you spell your name?" },
    { word: "cow",  hint: "A farm animal that gives milk",   sentence: "The cow eats grass in the field." },
    { word: "all",  hint: "Every single one",                sentence: "We ate all the pizza." },
    { word: "ball", hint: "A round object used in games",    sentence: "He threw the ball to his dog." },
    { word: "call",  hint: "To shout or use a phone",         sentence: "I will call you on the phone later." },
    { word: "add",   hint: "Put together; more",              sentence: "Add the numbers to get the total." },
    { word: "as",    hint: "Used to compare things",          sentence: "She is as tall as her brother." },
    { word: "ask",   hint: "Seek an answer to something",     sentence: "May I ask you a question?" },
    { word: "black", hint: "The darkest color",               sentence: "The night sky was a deep black." },
    { word: "blue",  hint: "The color of the sky",            sentence: "He wore a blue shirt today." },
    { word: "box",   hint: "A container with flat sides",     sentence: "Put your shoes in the box." },
    { word: "bug",   hint: "A small insect",                  sentence: "A bug landed on my arm." },
    { word: "bus",   hint: "A large vehicle that carries people", sentence: "I ride the bus to school." },
    { word: "but",   hint: "Showing a difference or exception", sentence: "I like apples but not pears." },
    { word: "by",    hint: "Next to something",               sentence: "She stood by the window." },
    { word: "did",   hint: "Past form of 'do'",               sentence: "Did you finish your homework?" },
    { word: "dig",   hint: "To make a hole in the ground",    sentence: "The dog dug a hole in the yard." },
    { word: "dim",   hint: "Not bright; slightly dark",       sentence: "The room was lit by a dim candle." },
    { word: "dip",   hint: "To put briefly into liquid",      sentence: "Dip the chip into the sauce." },
    { word: "dot",   hint: "A small round mark",              sentence: "Put a dot at the end of the sentence." },
    { word: "egg",   hint: "A round shell from a bird",       sentence: "I cracked an egg into the bowl." },
    { word: "end",   hint: "The final part of something",     sentence: "We reached the end of the trail." },
    { word: "fan",   hint: "It blows cool air",               sentence: "Turn on the fan — it's hot!" },
    { word: "fig",   hint: "A sweet fruit",                   sentence: "The fig tree grows in warm places." },
    { word: "fix",   hint: "To repair something",             sentence: "Can you fix my broken toy?" },
    { word: "fly",   hint: "To move through the air",         sentence: "Birds fly south for the winter." },
    { word: "fog",   hint: "A thick, low-lying cloud",        sentence: "The fog made it hard to see." },
    { word: "for",   hint: "In favor of; on behalf of",       sentence: "This gift is for you." },
    { word: "get",   hint: "To receive or obtain",            sentence: "Go get your coat." },
    { word: "got",   hint: "Past tense of get",               sentence: "He got a new book at the library." },
    { word: "had",   hint: "Past tense of have",              sentence: "She had a birthday party." },
    { word: "has",   hint: "Possesses or holds",              sentence: "He has a red bike." },
    { word: "her",   hint: "Belonging to a female",           sentence: "That is her favorite song." },
    { word: "him",   hint: "Refers to a male person",         sentence: "Call him when you arrive." },
    { word: "his",   hint: "Belonging to a male",             sentence: "His shoes are by the door." },
    { word: "hug",   hint: "To hold someone tightly with arms", sentence: "She gave me a warm hug." },
    { word: "hum",   hint: "To make a soft, steady sound",    sentence: "She began to hum a lullaby." },
    { word: "in",    hint: "Inside something",                sentence: "The cat is in the box." },
    { word: "jar",   hint: "A container with a wide opening", sentence: "She opened the jar of jam." },
    { word: "jet",   hint: "A fast airplane",                 sentence: "We watched the jet fly overhead." },
    { word: "job",   hint: "Work that you do",                sentence: "Cleaning my room is my job." },
    { word: "jog",   hint: "To run at a slow pace",           sentence: "I jog every morning before school." },
    { word: "lap",   hint: "The top of your legs when sitting", sentence: "The cat curled up on my lap." },
    { word: "leg",   hint: "The limb you walk on",            sentence: "She scraped her leg at recess." },
    { word: "let",   hint: "To allow or permit",              sentence: "Let me help you carry that." },
    { word: "lid",   hint: "A cover for a container",         sentence: "Put the lid back on the pot." },
    { word: "lip",   hint: "The edge of your mouth",          sentence: "She smiled and bit her lip." },
    { word: "log",   hint: "A thick piece of wood",           sentence: "We sat on a log by the fire." },
    { word: "lot",   hint: "A large amount",                  sentence: "There are a lot of stars tonight." },
    { word: "mud",   hint: "Wet, soft earth",                 sentence: "His boots were covered in mud." },
    { word: "nap",   hint: "A short sleep during the day",    sentence: "The baby took a long nap." },
    { word: "net",   hint: "A mesh used to catch things",     sentence: "The fisherman cast his net into the sea." },
    { word: "nod",   hint: "Move your head up and down",      sentence: "She gave a quick nod to agree." },
    { word: "not",   hint: "Used to make something negative", sentence: "I am not ready yet." },
    { word: "nut",   hint: "A hard-shelled seed",             sentence: "The squirrel ate the nut quickly." },
  ],
};
export default grade1;
