const grade3 = {
  grade: 3, roundSize: 10,
  pool: [
    { word: "accept",    hint: "Agree to receive something",      sentence: "Please accept this gift with a smile." },
    { word: "answer",    hint: "A reply to a question",           sentence: "She raised her hand to answer the question." },
    { word: "believe",   hint: "Think something is true",         sentence: "I believe you can do anything you try." },
    { word: "breathe",   hint: "Take air in and out",             sentence: "Take a moment to breathe deeply and relax." },
    { word: "center",    hint: "The middle point",                sentence: "Put the flower vase in the center of the table." },
    { word: "change",    hint: "Become different",                sentence: "The leaves change color every fall." },
    { word: "complete",  hint: "Finish entirely; whole",          sentence: "Make sure you complete all your homework." },
    { word: "danger",    hint: "Risk of harm",                    sentence: "The sign warned of danger on the icy road." },
    { word: "decide",    hint: "Make a choice",                   sentence: "It was hard to decide which book to read first." },
    { word: "different", hint: "Not the same as others",          sentence: "Every snowflake is different from all the rest." },
    { word: "enough",    hint: "A sufficient amount",             sentence: "Do we have enough bread for everyone?" },
    { word: "explain",   hint: "Make something clear",            sentence: "Can you explain how fractions work?" },
    { word: "famous",    hint: "Known by many people",            sentence: "She became famous for her beautiful paintings." },
    { word: "finally",   hint: "At the end; at last",             sentence: "After hours of hiking, we finally reached the top." },
    { word: "forward",   hint: "In the direction ahead",          sentence: "Take two steps forward and one step back." },
    { word: "friend",    hint: "Someone you like and trust",      sentence: "A good friend is hard to find." },
    { word: "important", hint: "Of great value or significance",  sentence: "It is important to tell the truth." },
    { word: "pretty",    hint: "Attractive to look at",           sentence: "The garden looks pretty in the springtime." },
    { word: "remember",  hint: "Bring back to mind",              sentence: "Please remember to bring your library book." },
    { word: "surprise",  hint: "Something unexpected",            sentence: "The birthday party was a wonderful surprise." },
    { word: "laugh",     hint: "To express amusement",            sentence: "That funny joke made me laugh aloud." },
    { word: "piece",     hint: "A part of something",             sentence: "May I have a piece of cake?" },
    { word: "quiet",     hint: "Making little or no noise",       sentence: "Please be quiet in the library." },
    { word: "quite",     hint: "To a certain degree; very",       sentence: "It is quite cold outside today." },
    { word: "build",     hint: "To construct something",          sentence: "They plan to build a new treehouse." },
    { word: "built",     hint: "Past tense of build",             sentence: "The birds built a nest in the tree." },
    { word: "wrong",     hint: "Incorrect or untrue",             sentence: "I guessed the wrong answer on the test." },
    { word: "young",     hint: "In an early stage of life",       sentence: "The young puppy loves to chew on shoes." },
    { word: "catch",     hint: "To capture or grab something",    sentence: "Try to catch the ball when I throw it." },
    { word: "guess",     hint: "To estimate without knowing",     sentence: "Can you guess how many jellybeans are in the jar?" },
    { word: "hurry",     hint: "To move quickly",                 sentence: "We must hurry so we won't be late." },
    { word: "listen",    hint: "To pay attention to sound",       sentence: "Always listen to your teacher." },
    { word: "minute",    hint: "Sixty seconds",                   sentence: "I will be ready in just one minute." },
    { word: "picture",   hint: "A drawing or photograph",         sentence: "She drew a beautiful picture of a house." },
    { word: "ready",     hint: "Prepared to do something",        sentence: "Are you ready to go to the park?" },
    { word: "sure",      hint: "Certain about something",         sentence: "I am sure I left my jacket here." },
    { word: "weather",   hint: "The condition of the air/sky",    sentence: "The weather is very sunny today." },
    { word: "whether",   hint: "Expressing a choice between options", sentence: "I don't know whether to stay or go." },
    { word: "woman",     hint: "An adult female person",          sentence: "The kind woman helped us find our dog." },
    { word: "women",     hint: "More than one woman",             sentence: "The women sang a beautiful song together." },
    { word: "break",     hint: "To smash or to pause",            sentence: "Be careful not to break the glass." },
    { word: "brake",     hint: "Device to slow or stop a vehicle",sentence: "Hit the brake to stop the bicycle." },
    { word: "buy",       hint: "To purchase with money",          sentence: "I want to buy an apple at the store." },
    { word: "write",     hint: "To form letters on a surface",    sentence: "I like to write letters to my grandmother." },
    { word: "author",    hint: "A person who writes a book",      sentence: " The author read from his newest book." },
    { word: "island",    hint: "Land surrounded by water",        sentence: "We took a boat to the small sandy island." },
    { word: "machine",   hint: "A device with moving parts",      sentence: "A car is a complex machine." },
    { word: "neighbor",  hint: "Someone living next door",        sentence: "Our next-door neighbor is very friendly." },
    { word: "often",     hint: "Many times",                      sentence: "We often visit the local library." },
    { word: "special",   hint: "Better or different from usual",  sentence: "Today is a very special day!" },
    { word: "accident",  hint: "An unexpected event causing harm",sentence: "He spilled the juice by accident." },
    { word: "address",   hint: "Where someone lives",             sentence: "What is your home address?" },
    { word: "balloon",   hint: "A colorful inflatable object",    sentence: "The red balloon floated away." },
    { word: "basket",    hint: "A container woven from strips",   sentence: "She carried a basket of apples." },
    { word: "battle",    hint: "A fight between two sides",       sentence: "The chess match felt like a great battle." },
    { word: "belong",    hint: "Be the property of someone",      sentence: "Does this jacket belong to you?" },
    { word: "blanket",   hint: "A large piece of material for warmth", sentence: "I wrapped myself in a warm blanket." },
    { word: "bought",    hint: "Past tense of buy",               sentence: "She bought a new pair of shoes." },
    { word: "button",    hint: "A small disk that fastens clothing", sentence: "The top button was missing from his coat." },
    { word: "careful",   hint: "Paying close attention",          sentence: "Be careful crossing the street." },
    { word: "castle",    hint: "A large, fortified building",     sentence: "The king lived in a grand castle." },
    { word: "certain",   hint: "Known beyond doubt",              sentence: "I am certain we passed the test." },
    { word: "challenge", hint: "A task that tests your abilities",sentence: "The spelling bee was a big challenge." },
    { word: "chapter",   hint: "A section of a book",             sentence: "We read the first chapter together." },
    { word: "cloud",     hint: "Water droplets floating in the sky", sentence: "The cloud blocked the sun." },
    { word: "color",     hint: "Red, blue, green — these are colors", sentence: "What is your favorite color?" },
    { word: "cotton",    hint: "A soft fabric from plants",       sentence: "Her shirt was made of pure cotton." },
    { word: "cousin",    hint: "A child of your aunt or uncle",   sentence: "My cousin is visiting this weekend." },
    { word: "crayon",    hint: "A colored stick for drawing",     sentence: "She drew a rainbow with her crayons." },
    { word: "create",    hint: "To make something new",           sentence: "We create art in class every Friday." },
    { word: "crowd",     hint: "A large group of people",         sentence: "A large crowd cheered at the concert." },
    { word: "desert",    hint: "A very dry, barren region",       sentence: "Camels live in the desert." },
    { word: "dinner",    hint: "The evening meal",                sentence: "Our family eats dinner together every night." },
    { word: "dragon",    hint: "A mythical fire-breathing creature", sentence: "The brave knight faced the fearsome dragon." },
    { word: "during",    hint: "Within the course of a time period", sentence: "Raise your hand during class if you are confused." },
    { word: "employ",    hint: "To give work to someone",         sentence: "The bakery will employ new workers in summer." },
    { word: "enjoyed",   hint: "Past tense of enjoy",             sentence: "We enjoyed the outdoor movie very much." },
    { word: "factory",   hint: "A building where things are made",sentence: "Cars are built in a factory." },
    { word: "family",    hint: "People related to you",           sentence: "Family is the most important thing." },
    { word: "gather",    hint: "Come together in one place",      sentence: "Everyone will gather in the gym for the show." },
    { word: "gentle",    hint: "Mild and kind in nature",         sentence: "Be gentle with the baby kitten." },
    { word: "golden",    hint: "Made of or resembling gold",      sentence: "The sun cast a golden light at sunset." },
    { word: "grammar",   hint: "The rules of a language",         sentence: "Good grammar helps you write clearly." },
    { word: "harbor",    hint: "A sheltered area of water for ships", sentence: "The boats docked safely in the harbor." },
    { word: "harvest",   hint: "Gathering ripe crops",            sentence: "The harvest was plentiful this autumn." },
    { word: "history",   hint: "The study of past events",        sentence: "We learn about history in school." },
    { word: "hollow",    hint: "Empty inside",                    sentence: "The squirrel hid nuts in the hollow tree." },
    { word: "hunger",    hint: "Feeling the need to eat",         sentence: "His hunger grew as lunchtime approached." },
    { word: "interest",  hint: "A feeling of curiosity",          sentence: "She has a strong interest in science." },
    { word: "journey",   hint: "A long trip from one place to another", sentence: "The wagon train began its long journey west." },
    { word: "jungle",    hint: "A thick tropical forest",         sentence: "The lion prowled through the jungle." },
    { word: "justice",   hint: "Fair treatment of all people",    sentence: "The judge worked hard for justice." },
    { word: "kitchen",   hint: "The room where food is cooked",   sentence: "The whole house smelled like the kitchen." },
    { word: "lantern",   hint: "A light inside a case",           sentence: "They carried a lantern through the dark cave." },
    { word: "lesson",    hint: "Something taught or learned",     sentence: "Today's lesson was about fractions." },
    { word: "letter",    hint: "A written message; also part of the alphabet", sentence: "She wrote a letter to her grandmother." },
    { word: "library",   hint: "A place full of books",           sentence: "We visit the library every week." },
    { word: "million",   hint: "The number 1,000,000",            sentence: "She read a million words this year." },
    { word: "mirror",    hint: "A reflective surface",            sentence: "He looked at himself in the mirror." },
    { word: "mistake",   hint: "Something done incorrectly",      sentence: "It is okay to make a mistake — just fix it." },
  ],
};
export default grade3;
