const grade2 = {
  grade: 2,
  roundSize: 10,
  pool: [
    { word: "about",   hint: "On the subject of something",       sentence: "Can you tell me about your day?" },
    { word: "again",   hint: "One more time",                     sentence: "Please say that again — I missed it." },
    { word: "always",  hint: "Every single time",                 sentence: "She always brushes her teeth before bed." },
    { word: "around",  hint: "In a circle or nearby",             sentence: "We walked around the whole park." },
    { word: "because", hint: "Used to give a reason",             sentence: "I wore a coat because it was cold." },
    { word: "before",  hint: "Earlier in time",                   sentence: "Wash your hands before you eat." },
    { word: "bring",   hint: "Carry something to a place",        sentence: "Please bring your book to class." },
    { word: "carry",   hint: "Hold and move something",           sentence: "She could carry two bags at once." },
    { word: "clean",   hint: "Not dirty",                         sentence: "His room is always clean and tidy." },
    { word: "drink",   hint: "Take liquid into your mouth",       sentence: "Remember to drink water every day." },
    { word: "eight",   hint: "The number after seven",            sentence: "There are eight apples in the basket." },
    { word: "every",   hint: "Each one without exception",        sentence: "Every student passed the test." },
    { word: "found",   hint: "Past tense of find",                sentence: "She found her lost pencil under the desk." },
    { word: "funny",   hint: "Makes you laugh",                   sentence: "He told a very funny joke." },
    { word: "green",   hint: "The color of grass",                sentence: "The frog was a bright green color." },
    { word: "jump",    hint: "Spring off the ground",             sentence: "The rabbit can jump really high." },
    { word: "know",    hint: "Have information about",            sentence: "I know all of my multiplication tables." },
    { word: "light",   hint: "Illumination; also not heavy",      sentence: "Turn on the light so I can read." },
    { word: "money",   hint: "Coins and bills you use to buy",    sentence: "He saved his money for a new toy." },
    { word: "never",   hint: "At no time",                        sentence: "I never go to bed without saying prayers." },
  ],
};
export default grade2;
