const grade11 = {
  grade: 11,
  roundSize: 15,
  pool: [
    { word: "abnegation",     hint: "The act of renouncing or rejecting something", sentence: "Her abnegation of personal comfort made her a great leader." },
    { word: "abscond",        hint: "Leave hurriedly and secretly to escape",     sentence: "The thief tried to abscond with the jewels but was caught." },
    { word: "abstemious",     hint: "Not self-indulgent, especially with food and drink", sentence: "An abstemious lifestyle helped the monk stay clear-minded." },
    { word: "abysmal",        hint: "Extremely bad; appalling",                   sentence: "The team's abysmal performance cost them the championship." },
    { word: "accolade",       hint: "An award or privilege given as recognition", sentence: "She received countless accolades for her groundbreaking research." },
    { word: "acumen",         hint: "The ability to make good judgments quickly", sentence: "His business acumen turned the small startup into an empire." },
    { word: "admonish",       hint: "Warn or reprimand someone firmly",           sentence: "The teacher admonished the students for talking during the test." },
    { word: "adulation",      hint: "Excessive admiration or praise",             sentence: "The rock star was overwhelmed by the crowd's adulation." },
    { word: "adversarial",    hint: "Involving conflicting parties; antagonistic",sentence: "The negotiation took on an adversarial tone from the beginning." },
    { word: "alacrity",       hint: "Brisk and cheerful readiness",               sentence: "She accepted the promotion with alacrity and excitement." },
    { word: "alluvial",       hint: "Relating to or derived from river deposits", sentence: "The alluvial plains were some of the richest farmlands in the region." },
    { word: "altruism",       hint: "Selfless concern for the well-being of others", sentence: "Her altruism was demonstrated through decades of volunteer work." },
    { word: "amalgam",        hint: "A mixture or blend of different elements",   sentence: "The treaty was an amalgam of compromises from both sides." },
    { word: "ambiguity",      hint: "The quality of being open to multiple interpretations", sentence: "The law's ambiguity led to years of conflicting court rulings." },
    { word: "amelioration",   hint: "The act of making something bad less severe",sentence: "The new program focused on the amelioration of poverty in the city." },
    { word: "anachronous",    hint: "Occurring out of its proper historical time",sentence: "The anachronous detail in the painting baffled art historians." },
    { word: "anathema",       hint: "Something greatly detested or loathed",      sentence: "Dishonesty was anathema to her professional values." },
    { word: "annihilate",     hint: "Destroy utterly; obliterate",                sentence: "The laser was designed to annihilate microbial contaminants." },
    { word: "antediluvian",   hint: "Of or belonging to the time before Noah's flood; very old", sentence: "His antediluvian views on technology frustrated the younger staff." },
    { word: "anthropology",   hint: "The study of human societies and cultures",  sentence: "She pursued a degree in anthropology to study ancient civilizations." },
    { word: "antiquated",     hint: "Old-fashioned or outdated",                  sentence: "The company's antiquated equipment slowed production greatly." },
    { word: "appellation",    hint: "A name or title",                            sentence: "The city earned the appellation 'City of Lights' centuries ago." },
    { word: "apposite",       hint: "Apt in the circumstances or in relation to",  sentence: "His apposite remarks made the lecture both relevant and memorable." },
    { word: "approbation",    hint: "Formal or official approval; praise",        sentence: "The board gave its approbation to the new budget plan." },
    { word: "arcane",         hint: "Understood by few; mysterious or secret",    sentence: "The arcane symbols on the ancient tablet puzzled researchers." },
    { word: "arduous",        hint: "Involving or requiring strenuous effort",    sentence: "The arduous climb took three days and tested every hiker." },
    { word: "argot",          hint: "The jargon or slang of a particular group",  sentence: "The teenager's argot was incomprehensible to her grandparents." },
    { word: "arrogate",       hint: "Take without the right to do so",            sentence: "He arrogated authority that had never been granted to him." },
    { word: "ascendancy",     hint: "Occupation of a position of power",          sentence: "The party rose to ascendancy after decades of struggle." },
    { word: "ascetic",        hint: "Severe self-discipline and abstention",      sentence: "The monk lived an ascetic life in the mountains." },
    { word: "asperity",       hint: "Harshness of tone or manner",                sentence: "She responded with surprising asperity to the mild criticism." },
    { word: "assiduous",      hint: "Showing great care and perseverance",        sentence: "Her assiduous preparation led to a flawless performance." },
    { word: "atavism",        hint: "The reappearance of traits from distant ancestors", sentence: "The scientist studied atavism to understand evolutionary biology." },
    { word: "attrition",      hint: "Gradual reduction in strength through sustained loss", sentence: "The organization experienced leadership attrition over five years." },
    { word: "audacious",      hint: "Showing willingness to take bold risks",     sentence: "The audacious plan to build a skyscraper in one year succeeded." },
    { word: "augment",        hint: "Make greater by adding to it; increase",     sentence: "The new policy was designed to augment the existing educational fund." },
    { word: "auspices",       hint: "The support and protection of a sponsor",    sentence: "The exhibition was held under the auspices of the national museum." },
    { word: "autocratic",     hint: "Taking no account of others' wishes; domineering", sentence: "The autocratic ruler dismissed all advice from his ministers." },
    { word: "avarice",        hint: "Extreme greed for wealth",                   sentence: "His avarice destroyed every business relationship he had." },
    { word: "avocation",      hint: "A hobby or minor occupation",                sentence: "His avocation as a watercolorist brought him peace on weekends." },
    { word: "axiomatic",      hint: "Self-evident or unquestionable",             sentence: "It is axiomatic that all humans need water to survive." },
    { word: "banality",       hint: "The state of being boring or obvious",       sentence: "The speech was full of banality and clichés that bored the crowd." },
    { word: "beguile",        hint: "Charm or enchant someone",                   sentence: "Her storytelling could beguile even the most skeptical audience." },
    { word: "belabor",        hint: "Argue or discuss a point in excessive detail",sentence: "There's no need to belabor the point — we all understand." },
    { word: "bemuse",         hint: "Puzzle or confuse someone",                  sentence: "The abstract artwork bemused nearly everyone at the gallery." },
    { word: "benediction",    hint: "A short prayer said at the end of a service",sentence: "The priest offered a benediction before everyone departed." },
    { word: "benighted",      hint: "In a state of pitiful intellectual or moral ignorance", sentence: "He was benighted in his understanding of modern medicine." },
    { word: "berate",         hint: "Scold or criticize someone angrily",         sentence: "She berated him harshly for forgetting such an important meeting." },
    { word: "blandish",       hint: "Coax with flattery and kind words",          sentence: "She tried to blandish the director into giving her the lead role." },
    { word: "blight",         hint: "A plant disease; anything that spoils or damages", sentence: "The corrupt official was a blight on the city's progress." },
    { word: "bolster",        hint: "Strengthen or support",                      sentence: "Extra evidence helped bolster the case against the defendant." },
  ],
};
export default grade11;
