const grade9 = {
  grade: 9,
  roundSize: 15,
  pool: [
    { word: "acquiesce",      hint: "Accept reluctantly but without protest",    sentence: "Rather than argue further, she chose to acquiesce to the ruling." },
    { word: "ambivalent",     hint: "Having mixed or contradictory feelings",    sentence: "He felt ambivalent about leaving his hometown for college." },
    { word: "anachronism",    hint: "Something belonging to a wrong time period",sentence: "A smartphone in a medieval film would be an obvious anachronism." },
    { word: "antithesis",     hint: "The exact opposite of something",           sentence: "Greed is the antithesis of generosity." },
    { word: "apocryphal",     hint: "Of doubtful authenticity; widely believed but probably untrue", sentence: "The story about the president's childhood is largely apocryphal." },
    { word: "cacophony",      hint: "A harsh, discordant mixture of sounds",     sentence: "The street market was filled with a cacophony of vendors yelling." },
    { word: "capricious",     hint: "Given to sudden changes; impulsive",        sentence: "The capricious weather ruined our picnic three times." },
    { word: "cathartic",      hint: "Providing emotional release or relief",     sentence: "Writing in her journal was a deeply cathartic experience." },
    { word: "circumlocution", hint: "The use of many words where few would do",  sentence: "His circumlocution made the simple answer very confusing." },
    { word: "condescending",  hint: "Showing a patronizing superiority",         sentence: "Her condescending tone made everyone on the team feel undervalued." },
    { word: "corroborate",    hint: "Confirm or support facts or a statement",   sentence: "The security footage helped corroborate the eyewitness account." },
    { word: "cynicism",       hint: "An inclination to question; distrust of motives", sentence: "After years of disappointment, cynicism crept into his outlook." },
    { word: "demagoguery",    hint: "Appealing to desires/prejudices rather than reason", sentence: "The politician's demagoguery divided the community further." },
    { word: "didactic",       hint: "Intended to teach or give instruction",     sentence: "The novel was so didactic that it read more like a textbook." },
    { word: "duplicity",      hint: "Deceitfulness; double-dealing",             sentence: "His duplicity was exposed when both sides compared notes." },
    { word: "ebullience",     hint: "The quality of being cheerful and full of energy", sentence: "Her ebullience every morning was contagious and uplifting." },
    { word: "efficacious",    hint: "Successful in producing the desired result", sentence: "The new medicine proved highly efficacious in clinical trials." },
    { word: "ephemeral",      hint: "Lasting for a very short time",             sentence: "Trends on social media are often ephemeral, gone in a week." },
    { word: "equivocate",     hint: "Use ambiguous language to avoid committing",sentence: "Stop equivocating — just give me a direct answer." },
    { word: "erudite",        hint: "Having or showing great knowledge",         sentence: "The erudite professor could speak at length on any topic." },
    { word: "ethereal",       hint: "Extremely delicate and light; heavenly",    sentence: "The music had an ethereal quality that filled the cathedral." },
    { word: "excoriate",      hint: "Censure or criticize severely",             sentence: "The media excoriate d the CEO for his poor response." },
    { word: "exigent",        hint: "Pressing; requiring immediate action",      sentence: "The exigent circumstances required an immediate response." },
    { word: "fallacious",     hint: "Based on a mistaken belief or faulty logic",sentence: "His fallacious argument collapsed under close examination." },
    { word: "fatuous",        hint: "Silly and pointless",                       sentence: "She dismissed his fatuous comment with a roll of her eyes." },
    { word: "feckless",       hint: "Lacking initiative or strength of character",sentence: "His feckless attitude made him unreliable on any project." },
    { word: "fervent",        hint: "Having or displaying passionate intensity", sentence: "She was a fervent supporter of education reform." },
    { word: "forthright",     hint: "Direct and outspoken; frank",               sentence: "I appreciate his forthright way of telling me the truth." },
    { word: "garrulous",      hint: "Excessively talkative, especially about trivial things", sentence: "The garrulous neighbor talked for an hour straight." },
    { word: "grandiloquent",  hint: "Pompous or extravagant in language",        sentence: "His grandiloquent speech bored the simple, plain-spoken audience." },
    { word: "hegemony",       hint: "Leadership or dominance of one country over others", sentence: "The nation sought cultural hegemony through its film exports." },
    { word: "iconoclast",     hint: "A person who challenges accepted norms",    sentence: "The young artist was an iconoclast who broke every rule of the genre." },
    { word: "impetuous",      hint: "Acting quickly without thinking",           sentence: "His impetuous decision to quit cost him the job offer." },
    { word: "implacable",     hint: "Unable to be appeased or satisfied",        sentence: "The implacable judge showed no mercy during sentencing." },
    { word: "incoherent",     hint: "Expressed in a confusing way; unclear",     sentence: "His speech was incoherent due to his extreme exhaustion." },
    { word: "incongruent",    hint: "Not in harmony; at odds",                   sentence: "Her cheerful outfit was incongruent with the solemn occasion." },
    { word: "indolent",       hint: "Wanting to avoid activity; lazy",           sentence: "The indolent student waited until the last minute for everything." },
    { word: "ineffable",      hint: "Too great or extreme to be expressed",      sentence: "The beauty of the Aurora Borealis was simply ineffable." },
    { word: "inimical",       hint: "Tending to obstruct or harm; hostile",      sentence: "Pollution is inimical to human health and wellbeing." },
    { word: "insidious",      hint: "Proceeding in a gradual, harmful way",      sentence: "The insidious spread of misinformation is hard to stop." },
    { word: "insolent",       hint: "Showing a rude and arrogant lack of respect", sentence: "The insolent student was sent to the principal's office." },
    { word: "intransigent",   hint: "Refusing to change one's views",            sentence: "The intransigent negotiator refused every proposed compromise." },
    { word: "invective",      hint: "Insulting or abusive language",             sentence: "The argument ended in a torrent of invective." },
    { word: "irascible",      hint: "Having or showing a tendency to be easily angered", sentence: "The irascible coach screamed at the referee every game." },
    { word: "laconic",        hint: "Using very few words to express something", sentence: "His response was laconic — just a single nod." },
    { word: "loquacious",     hint: "Tending to talk a great deal",              sentence: "The loquacious guest dominated every conversation at dinner." },
    { word: "lugubrious",     hint: "Looking or sounding sad and dismal",        sentence: "The violinist played a lugubrious melody at the funeral." },
    { word: "magnanimous",    hint: "Very generous or forgiving",                sentence: "The magnanimous winner congratulated all of his competitors." },
    { word: "maladroit",      hint: "Inefficient or clumsy in action or thought",sentence: "The maladroit assistant kept spilling things at the ceremony." },
    { word: "mendacious",     hint: "Not telling the truth; lying",              sentence: "The mendacious politician was finally exposed by investigators." },
    { word: "mercurial",      hint: "Subject to sudden or unpredictable changes",sentence: "Her mercurial moods made it difficult to plan anything." },
  ],
};
export default grade9;
