const grade5 = {
  grade: 5, roundSize: 12,
  pool: [
    { word: "abundance",      hint: "A very large amount of something",        sentence: "The garden produced an abundance of vegetables this year." },
    { word: "accomplishment",  hint: "A completed achievement",                sentence: "Learning to play piano was her greatest accomplishment." },
    { word: "anonymous",       hint: "Without a known name",                   sentence: "The generous donation was made by an anonymous person." },
    { word: "approximately",   hint: "Close to; roughly",                      sentence: "The drive takes approximately two hours." },
    { word: "circumstance",    hint: "A condition that affects a situation",   sentence: "Under no circumstance should you leave without telling me." },
    { word: "collaboration",   hint: "Working together with others",           sentence: "The project was a collaboration between three schools." },
    { word: "commemorate",     hint: "Honor the memory of something",          sentence: "The statue was built to commemorate fallen soldiers." },
    { word: "communicate",     hint: "Share information with others",          sentence: "It is important to communicate clearly and kindly." },
    { word: "comparison",      hint: "Examining similarities and differences", sentence: "The comparison showed that the new book is better." },
    { word: "consequence",     hint: "A result of an action",                  sentence: "Every choice has a consequence, good or bad." },
    { word: "curiosity",       hint: "Desire to know or learn",                sentence: "Her curiosity led her to read every book in the library." },
    { word: "definitely",      hint: "Without any doubt",                      sentence: "I will definitely be at your performance tonight." },
    { word: "demonstrate",     hint: "Show how something works",               sentence: "The teacher will demonstrate the science experiment first." },
    { word: "determination",   hint: "Firmly decided; persistence",            sentence: "With determination, he practiced every day until he won." },
    { word: "exaggerate",      hint: "Make something seem bigger than it is",  sentence: "Don't exaggerate — it wasn't that scary!" },
    { word: "fascinate",       hint: "Hold someone's interest strongly",       sentence: "The documentary about oceans never failed to fascinate me." },
    { word: "knowledge",       hint: "Facts and understanding gained",         sentence: "Reading builds knowledge that stays with you forever." },
    { word: "punctuation",     hint: "Marks used in writing like commas",      sentence: "Correct punctuation makes your writing much easier to read." },
    { word: "significant",     hint: "Important or meaningful",                sentence: "The discovery was a significant moment in science." },
    { word: "transparent",     hint: "Able to be seen through; open",          sentence: "Good leaders are transparent about their decisions." },
    { word: "absolutely",      hint: "With no qualification, restriction",     sentence: "I am absolutely sure we locked the door." },
    { word: "academic",        hint: "Relating to education and scholarship",  sentence: "The school offers many academic programs." },
    { word: "accepting",       hint: "Consenting to receive or undertake",     sentence: "He was accepting of their apology." },
    { word: "accidental",      hint: "Happening by chance",                    sentence: "The spill on the carpet was completely accidental." },
    { word: "accomplish",      hint: "Achieve or complete successfully",       sentence: "You can accomplish anything if you work hard." },
    { word: "actually",        hint: "As the truth or facts of a situation",   sentence: "I thought it was raining, but actually it wasn't." },
    { word: "additional",      hint: "Added, extra, or supplementary",         sentence: "We will need additional chairs for our guests." },
    { word: "address",         hint: "The particulars of where someone lives", sentence: "Can you give me your mailing address?" },
    { word: "advertise",       hint: "Describe or draw attention to a product",sentence: "They plan to advertise the new game on television." },
    { word: "altogether",      hint: "Completely; totally",                    sentence: "I stopped eating candy altogether." },
    { word: "ambassador",      hint: "An accredited diplomat sent by a country",sentence: "The ambassador represented her nation with honor." },
    { word: "analysis",        hint: "Detailed examination of the parts",      sentence: "The scientist presented his analysis of the data." },
    { word: "analyze",         hint: "Discover or reveal through detailed exam",sentence: "We must analyze the results before deciding." },
    { word: "apparent",        hint: "Clearly visible or understood",          sentence: "It was apparent that he was feeling much better." },
    { word: "appreciate",      hint: "Recognize the full worth of",            sentence: "I appreciate all the help you've given me." },
    { word: "appropriate",     hint: "Suitable or proper in the circumstances",sentence: "Is this dress appropriate for a wedding?" },
    { word: "architecture",    hint: "The art or practice of designing buildings", sentence: "The ancient architecture of the city is beautiful." },
    { word: "boundary",        hint: "A line that marks the limits of an area",sentence: "The river forms a boundary between the two states." },
    { word: "brilliant",       hint: "Exceptionally clever or talented",       sentence: "Albert Einstein was a brilliant scientist." },
    { word: "briefly",         hint: "For a short time",                       sentence: "We stopped briefly to rest on our hike." },
    { word: "calculate",       hint: "Determine the amount or number",         sentence: "Can you calculate the total cost of the items?" },
    { word: "campaign",        hint: "An organized course of action",          sentence: "The campaign to clean up the park was a success." },
    { word: "capacity",        hint: "The maximum amount that something can contain", sentence: "The stadium was filled to capacity." },
    { word: "category",        hint: "A class or division of people or things",sentence: "What category does this book belong in?" },
    { word: "challenge",       hint: "A call to take part in a contest",       sentence: "The math puzzle was a fun challenge." },
    { word: "character",       hint: "The mental and moral qualities of an individual", sentence: "She has such a strong character and kind heart." },
    { word: "collection",      hint: "The action or process of collecting someone or something", sentence: "He showed us his amazing coin collection." },
    { word: "combination",     hint: "A joining or merging of different parts",sentence: "The safe required a secret combination to open." },
    { word: "commercial",      hint: "Concerned with or engaged in commerce",  sentence: "We watched a funny commercial on television." },
    { word: "committee",       hint: "A group of people appointed for a specific function", sentence: "The committee meets every Tuesday to discuss school events." },
  ],
};
export default grade5;
