const grade12 = {
  grade: 12,
  roundSize: 15,
  pool: [
    { word: "abeyance",       hint: "A state of temporary disuse or suspension", sentence: "Plans for the new library were held in abeyance during the budget crisis." },
    { word: "abjure",         hint: "Solemnly renounce or reject",               sentence: "The dictator was forced to abjure his claim to the throne." },
    { word: "abnegation",     hint: "Renunciation of comfort or pleasure",       sentence: "The soldier's abnegation of personal comfort was truly admirable." },
    { word: "abominate",      hint: "Detest; loathe greatly",                    sentence: "She absolutely abominated cruelty in any form." },
    { word: "absolution",     hint: "Formal forgiveness of sins",                sentence: "He sought absolution for the choices he had made years before." },
    { word: "abstruse",       hint: "Difficult to understand; obscure",           sentence: "The treatise was so abstruse that only specialists could follow it." },
    { word: "accretion",      hint: "Growth by the gradual accumulation of layers",sentence: "The reef experienced accretion as coral built up over centuries." },
    { word: "acrimony",       hint: "Bitterness or ill feeling, especially in speech", sentence: "The divorce proceedings were filled with acrimony on both sides." },
    { word: "adumbrate",      hint: "Give a faint outline or indication of",     sentence: "The architect adumbrated his vision before presenting the final plans." },
    { word: "aggrandize",     hint: "Increase power, status, or wealth",         sentence: "His writing was designed to aggrandize himself, not to inform." },
    { word: "alacrity",       hint: "Brisk and cheerful readiness",              sentence: "The troops responded to the command with impressive alacrity." },
    { word: "alexithymia",    hint: "Difficulty identifying and describing emotions", sentence: "Alexithymia made it hard for him to process grief effectively." },
    { word: "allocution",     hint: "A formal speech giving advice or a warning",sentence: "The judge delivered a stern allocution before announcing the sentence." },
    { word: "alluvium",       hint: "Soil deposited by flowing water",           sentence: "The alluvium made the floodplains exceptionally fertile." },
    { word: "amalgamation",   hint: "The action of combining two things",        sentence: "The amalgamation of the two firms created industry-wide disruption." },
    { word: "ambivalence",    hint: "Uncertainty or fluctuation of feeling",     sentence: "His ambivalence about the role was clear from his hesitant performance." },
    { word: "amelioration",   hint: "The act of making something bad less severe",sentence: "The new drug showed significant amelioration of the symptoms." },
    { word: "amenable",       hint: "Responsive and open to suggestion",         sentence: "He was amenable to changing the plan once the risks were explained." },
    { word: "amorphous",      hint: "Without a clearly defined form",            sentence: "The amorphous blob of clay slowly took shape in the sculptor's hands." },
    { word: "anodyne",        hint: "Not likely to cause offense; inoffensive",  sentence: "His anodyne remarks failed to rally anyone to the cause." },
    { word: "anomie",         hint: "Social instability resulting from breakdown of standards", sentence: "Rapid industrialization caused social anomie in the otherwise rural community." },
    { word: "antinomy",       hint: "A contradiction between two laws or principles", sentence: "The philosopher spent years resolving the antinomy of free will and determinism." },
    { word: "aphorism",       hint: "A pithy observation expressing a truth",    sentence: "His lectures were full of memorable aphorisms the students quoted for years." },
    { word: "apodictic",      hint: "Clearly established or beyond dispute",     sentence: "The mathematical proof was apodictic and irrefutable." },
    { word: "apostate",       hint: "A person who abandons a belief or principle",sentence: "He was branded an apostate by his former political allies." },
    { word: "approbation",    hint: "Approval or praise, especially formally",   sentence: "The project received the committee's full approbation." },
    { word: "arbitrage",      hint: "The practice of taking advantage of price differences", sentence: "The investment firm profited enormously through international arbitrage." },
    { word: "archetypal",     hint: "Very typical of its kind; quintessential",  sentence: "The detective story had an archetypal hero — flawed but brilliant." },
    { word: "arrant",         hint: "Complete; utter; thoroughgoing",            sentence: "The accusation was arrant nonsense that nobody believed." },
    { word: "asperity",       hint: "Roughness of texture; harshness of manner", sentence: "He replied to their questions with surprising asperity." },
    { word: "assiduous",      hint: "Careful and persistent in work or effort",  sentence: "The assiduous junior lawyer left no case detail unexplored." },
    { word: "attrition",      hint: "A gradual process of wearing down through pressure", sentence: "War of attrition slowly depleted both armies of their resources." },
    { word: "avaricious",     hint: "Having or showing an extreme greed for wealth", sentence: "The avaricious landlord raised the rent every six months." },
    { word: "axiom",          hint: "A statement or proposition self-evidently true",sentence: "It is an axiom in economics that supply and demand are interrelated." },
    { word: "banal",          hint: "So lacking in originality as to be obvious", sentence: "The banal pop song had been heard a million times already." },
    { word: "baroque",        hint: "Highly ornate and extravagant in style",    sentence: "The baroque architecture of the cathedral overwhelmed the tourists." },
    { word: "bellicosity",    hint: "Inclination to start quarrels or wars",     sentence: "His bellicosity made collaboration on any project nearly impossible." },
    { word: "beneficence",    hint: "Generous doing of good; kindness",          sentence: "The foundation was known throughout the region for its beneficence." },
    { word: "benign",         hint: "Gentle and kind; not harmful",              sentence: "The tumor was benign — a welcome relief for the family." },
    { word: "bibliophile",    hint: "A person who collects or has a great love of books", sentence: "As a bibliophile, she owned thousands of rare first editions." },
    { word: "bifurcation",    hint: "The division of something into two branches",sentence: "There was a clear bifurcation in the debate between traditionalists and modernists." },
    { word: "cabal",          hint: "A secret political clique or faction",      sentence: "The cabal of advisors worked quietly to undermine the prime minister." },
    { word: "cachet",         hint: "A mark of prestige; official approval",     sentence: "Publishing with that house gave the author immediate cachet." },
    { word: "cadence",        hint: "A modulation or inflection of the voice",   sentence: "His lyrical cadence made even a grocery list sound poetic." },
    { word: "calumny",        hint: "The making of false and defamatory statements", sentence: "The politician sued the tabloid for persistent calumny." },
    { word: "canard",         hint: "An unfounded rumor or story",               sentence: "The canard spread so quickly that it became accepted as fact." },
    { word: "capitulation",   hint: "The act of surrendering under terms agreed upon", sentence: "The capitulation of the outpost ended a three-week standoff." },
    { word: "catalytic",      hint: "Causing or accelerating a change",          sentence: "The invention served as a catalytic force in transforming the industry." },
    { word: "causality",      hint: "The relationship between cause and effect",  sentence: "Philosophy students debated the causality of human behavior." },
    { word: "cerebral",       hint: "Intellectual rather than emotional",        sentence: "The cerebral novel demanded total focus and deep reading." },
  ],
};
export default grade12;
