const grade8 = {
  grade: 8, roundSize: 15,
  pool: [
    { word: "abstinence",       hint: "Self-restraint from indulging a desire",        sentence: "Abstinence from social media improved her focus dramatically." },
    { word: "acrimony",         hint: "Bitterness or ill feeling",                     sentence: "The debate ended with acrimony on both sides." },
    { word: "anomalous",        hint: "Deviating from what is standard",               sentence: "The anomalous result prompted the scientists to repeat the test." },
    { word: "apprehension",     hint: "Anxiety or fear about a future event",          sentence: "She waited with apprehension for the judge's decision." },
    { word: "bellicose",        hint: "Demonstrating aggression; eager to fight",      sentence: "His bellicose attitude made every conversation a confrontation." },
    { word: "circumspect",      hint: "Wary and unwilling to take risks",              sentence: "A circumspect investor never puts all their money in one place." },
    { word: "cogent",           hint: "Clear, logical, and convincing",                sentence: "She made a cogent argument that convinced even the skeptics." },
    { word: "complacency",      hint: "Smug and uncritical self-satisfaction",         sentence: "Complacency after early success led to their eventual failure." },
    { word: "conscientious",    hint: "Wishing to do one's work thoroughly and well",  sentence: "A conscientious student checks their work before submitting." },
    { word: "disingenuous",     hint: "Not candid or sincere; insincere",              sentence: "His apology felt disingenuous because he never changed his behavior." },
    { word: "frivolous",        hint: "Not having any serious purpose",                sentence: "The judge dismissed the frivolous lawsuit immediately." },
    { word: "idiosyncratic",    hint: "Peculiar to the individual; quirky",            sentence: "His idiosyncratic teaching style made the class unforgettable." },
    { word: "immutable",        hint: "Unchanging over time or impossible to change",  sentence: "Certain natural laws are immutable and cannot be negotiated." },
    { word: "indignation",      hint: "Anger at something unjust or unfair",           sentence: "The crowd expressed their indignation at the unfair verdict." },
    { word: "malfeasance",      hint: "Wrongdoing, especially by a public official",   sentence: "The official resigned amid accusations of malfeasance in office." },
    { word: "meticulous",       hint: "Showing great attention to detail",             sentence: "The meticulous editor caught every error in the manuscript." },
    { word: "pedantic",         hint: "Overly concerned with minor, trivial details",  sentence: "His pedantic corrections annoyed the other team members." },
    { word: "prerogative",      hint: "A right or privilege belonging to a person",    sentence: "It is your prerogative to choose how you spend your free time." },
    { word: "truculent",        hint: "Eager or quick to argue or fight",              sentence: "The truculent child argued with every instruction given." },
    { word: "ubiquitous",       hint: "Present, appearing, or found everywhere",       sentence: "Smartphones are now ubiquitous in modern daily life." },
    { word: "adept",            hint: "Very skilled or proficient at something",       sentence: "She is highly adept at solving complex puzzles." },
    { word: "adjacent",         hint: "Next to or adjoining something else",           sentence: "They stayed in adjacent rooms at the hotel." },
    { word: "adroit",           hint: "Clever or skillful in using the hands or mind", sentence: "He was an adroit negotiator, securing a great deal." },
    { word: "alacrity",         hint: "Brisk and cheerful readiness",                  sentence: "She accepted the promotion with alacrity." },
    { word: "alleviate",        hint: "Make suffering, deficiency, or a problem less severe", sentence: "The medicine helped alleviate the pain instantly." },
    { word: "allude",           hint: "Suggest or call attention to indirectly",       sentence: "She continued to allude to a secret without revealing it." },
    { word: "altar",            hint: "The table in a Christian church",               sentence: "The candles on the altar flickered gently." },
    { word: "alter",            hint: "Change or cause to change in character or composition", sentence: "He had to alter his suit because he lost weight." },
    { word: "ameliorate",       hint: "Make something bad or unsatisfactory better",   sentence: "New reforms were passed to ameliorate working conditions." },
    { word: "amenity",          hint: "A desirable or useful feature or facility",     sentence: "The hotel offers a swimming pool as a core amenity." },
    { word: "amiable",          hint: "Having or displaying a friendly and pleasant manner", sentence: "The host was amiable and made everyone feel welcome." },
    { word: "analogy",          hint: "A comparison between two things for explanation", sentence: "The teacher used an analogy to explain the difficult concept." },
    { word: "anarchy",          hint: "A state of disorder due to absence of authority", sentence: "Without leadership, the country quickly descended into anarchy." },
    { word: "anatomy",          hint: "The branch of science concerned with the bodily structure", sentence: "Medical students must deeply study human anatomy." },
    { word: "ancestry",         hint: "One's family or ethnic descent",                sentence: "He researched his ancestry using old census records." },
    { word: "anomaly",          hint: "Something that deviates from what is standard", sentence: "The blizzard in May was a remarkable weather anomaly." },
    { word: "antagonist",       hint: "A person who actively opposes or is hostile",   sentence: "The hero finally defeated the story's antagonist." },
    { word: "apathy",           hint: "Lack of interest, enthusiasm, or concern",      sentence: "Widespread voter apathy led to a very low turnout." },
    { word: "appease",          hint: "Pacify or placate someone by giving in to demands", sentence: "The manager gave a discount to appease the angry customer." },
    { word: "arbitrary",        hint: "Based on random choice or personal whim",       sentence: "The rules seemed completely arbitrary and unfair." },
    { word: "ascertain",        hint: "Find something out for certain",                sentence: "The detective tried to ascertain the timeline of events." },
    { word: "ascetic",          hint: "Characterized by or suggesting the practice of severe self-discipline", sentence: "The monk lived a quiet, ascetic life in the mountains." },
    { word: "assess",           hint: "Evaluate or estimate the nature, ability, or quality of", sentence: "The insurance agent arrived to assess the flood damage." },
    { word: "assiduous",        hint: "Showing great care and perseverance",           sentence: "Her assiduous research led to a major scientific breakthrough." },
    { word: "astute",           hint: "Having an ability to accurately assess situations", sentence: "He was an astute businessman who rarely made mistakes." },
    { word: "audacious",        hint: "Showing a willingness to take surprisingly bold risks", sentence: "The explorer made an audacious attempt to cross the desert." },
    { word: "augment",          hint: "Make something greater by adding to it",        sentence: "He picked up an extra job to augment his income." },
    { word: "auspicious",       hint: "Conducive to success; favorable",               sentence: "The sunny weather made for an auspicious start to the trip." },
    { word: "authentic",        hint: "Of undisputed origin; genuine",                 sentence: "Experts verified that the painting was an authentic Picasso." },
    { word: "avarice",          hint: "Extreme greed for wealth or material gain",     sentence: "His avarice eventually caused him to lose all his friends." },
    { word: "aversion",         hint: "A strong dislike or disinclination",            sentence: "She had a deep aversion to dishonesty of any kind." },
    { word: "axiom",            hint: "A statement regarded as self-evidently true",   sentence: "It is an axiom that practice makes a person better." },
    { word: "banal",            hint: "So lacking in originality as to be obvious",    sentence: "His writing was dismissed as banal and predictable." },
    { word: "belittle",         hint: "Make someone feel less important",              sentence: "Never belittle the effort of someone trying to learn." },
    { word: "benign",           hint: "Gentle and kind; not harmful",                  sentence: "The growth turned out to be entirely benign." },
    { word: "bewilderment",     hint: "A feeling of being confused",                   sentence: "His bewilderment showed clearly in his expression." },
    { word: "blatant",          hint: "Done openly and unashamedly",                   sentence: "The mistake was a blatant error that everyone noticed." },
    { word: "brevity",          hint: "Concise and exact use of words",                sentence: "Brevity is the soul of wit, as Shakespeare once said." },
    { word: "buoyant",          hint: "Able to stay afloat; cheerful and optimistic",  sentence: "She remained buoyant despite all the obstacles she faced." },
    { word: "cacophony",        hint: "A harsh, discordant mixture of sounds",         sentence: "The cafeteria was a cacophony of overlapping voices." },
    { word: "callous",          hint: "Showing or having an insensitive lack of care", sentence: "His callous rejection hurt her feelings deeply." },
    { word: "candor",           hint: "The quality of being open and honest",          sentence: "I appreciated the professor's candor about the difficulty level." },
    { word: "capitulate",       hint: "Cease to resist; surrender",                    sentence: "Faced with overwhelming evidence, he finally capitulated." },
    { word: "capricious",       hint: "Given to sudden unpredictable changes",         sentence: "The school's capricious schedule confused everyone." },
    { word: "caustic",          hint: "Sarcastic in a scathing way",                   sentence: "His caustic remarks made the atmosphere tense." },
    { word: "chicanery",        hint: "The use of trickery to achieve goals",          sentence: "The contract was riddled with chicanery and deceptions." },
    { word: "chronicle",        hint: "A factual written account of events",           sentence: "The book was a fascinating chronicle of the Civil War." },
    { word: "clamor",           hint: "A loud and confused noise",                     sentence: "The clamor of the protest could be heard from blocks away." },
    { word: "clandestine",      hint: "Kept secret or done secretively",               sentence: "The clandestine operation was known only to three people." },
    { word: "colossal",         hint: "Extremely large; enormous",                     sentence: "Winning the championship was a colossal achievement." },
    { word: "compel",           hint: "Force or oblige someone to do something",       sentence: "Honesty compels me to admit I was wrong." },
    { word: "complacent",       hint: "Smug and uncritical of oneself",                sentence: "The champion became complacent and lost to the underdog." },
    { word: "condescend",       hint: "Show a patronizing attitude toward others",     sentence: "Do not condescend to students who ask basic questions." },
    { word: "conformity",       hint: "Compliance with conventions or rules",          sentence: "Blind conformity discourages creativity and innovation." },
    { word: "conjecture",       hint: "Forming an opinion without full evidence",      sentence: "His assumption was pure conjecture without any proof." },
    { word: "convoluted",       hint: "Extremely complex and difficult to follow",      sentence: "The convoluted instructions left everyone more confused." },
    { word: "copious",          hint: "Abundant in supply; more than enough",          sentence: "She took copious notes throughout the entire lecture." },
    { word: "cordial",          hint: "Warm and friendly in manner",                   sentence: "The host welcomed every guest with a cordial handshake." },
    { word: "credible",         hint: "Able to be believed; convincing",               sentence: "The witness's account was entirely credible and detailed." },
    { word: "cynicism",         hint: "A distrustful attitude toward motives of others",sentence: "His cynicism grew from years of broken political promises." },
    { word: "dauntless",        hint: "Showing fearlessness and determination",        sentence: "The dauntless explorer ventured into uncharted territory." },
    { word: "decadence",        hint: "Moral or cultural decline",                     sentence: "Historians debated whether decadence caused the empire's fall." },
    { word: "deference",        hint: "Humble submission and respect",                 sentence: "She showed great deference to the elder members of the board." },
    { word: "deleterious",      hint: "Causing harm or damage",                        sentence: "Excessive screen time can be deleterious to sleep quality." },
    { word: "denounce",         hint: "Publicly declare to be wrong or evil",          sentence: "The senator chose to publicly denounce the corrupt practice." },
    { word: "derisive",         hint: "Expressing contempt or ridicule",               sentence: "His derisive laughter stung more than any harsh words." },
    { word: "despicable",       hint: "Deserving hatred and contempt",                 sentence: "The bully's behavior was utterly despicable." },
    { word: "devout",           hint: "Having or showing deep religious feeling",      sentence: "She was a devout woman who prayed every single morning." },
    { word: "dichotomy",        hint: "A division into two opposite groups",           sentence: "The novel explored the dichotomy between order and chaos." },
    { word: "didactic",         hint: "Intended to teach or give instruction",         sentence: "The fable was didactic, ending with a clear moral lesson." },
    { word: "discordant",       hint: "Disagreeing or incongruous",                    sentence: "The discordant notes in the symphony stood out sharply." },
    { word: "disdain",          hint: "The feeling that something is unworthy",        sentence: "He looked upon laziness with utter disdain." },
    { word: "disparage",        hint: "Regard or represent as being of little worth",  sentence: "It's cruel to disparage someone's hard-earned effort." },
    { word: "dissent",          hint: "Hold or express opinions contrary to popular views", sentence: "The lone vote of dissent sparked a great debate." },
    { word: "dogma",            hint: "A principle laid down as authoritative truth",  sentence: "Religious dogma has shaped entire civilizations." },
    { word: "dour",             hint: "Relentlessly severe, stern, or gloomy",         sentence: "The dour banker never cracked so much as a smile." },
    { word: "dupe",             hint: "Deceive or trick someone",                      sentence: "The scammer tried to dupe the elderly man into sending money." },
    { word: "duplicitous",      hint: "Deceitful in speech or conduct",               sentence: "His duplicitous nature was eventually exposed to everyone." },
    { word: "ebullient",        hint: "Cheerful and full of energy",                   sentence: "Her ebullient personality lit up every room she walked into." },
    { word: "edify",            hint: "Instruct or improve morally or intellectually", sentence: "Great literature should both entertain and edify the reader." },
  ],
};
export default grade8;
