const gradeK = {
  grade: 0,
  roundSize: 6,
  pool: [
    { word: "a",    hint: "A word used before nouns",       sentence: "I have a dog." },
    { word: "an",   hint: "Used before a vowel sound",      sentence: "She ate an apple." },
    { word: "at",   hint: "A small word showing place",     sentence: "I am at home." },
    { word: "am",   hint: "A form of the word 'be'",        sentence: "I am happy today." },
    { word: "as",   hint: "Used for comparing things",      sentence: "It is as cold as ice." },
    { word: "be",   hint: "To exist",                       sentence: "I want to be kind." },
    { word: "do",   hint: "To perform something",           sentence: "Do your best work!" },
    { word: "go",   hint: "To move or travel",              sentence: "Let us go to the park." },
    { word: "he",   hint: "A word for a boy or man",        sentence: "He is my brother." },
    { word: "if",   hint: "Used for a condition",           sentence: "If it rains, we stay in." },
    { word: "in",   hint: "Inside of something",            sentence: "The cat is in the box." },
    { word: "is",   hint: "A form of the word 'be'",        sentence: "She is my friend." },
    { word: "it",   hint: "Used for a thing",               sentence: "It is a sunny day." },
    { word: "me",   hint: "Talking about yourself",         sentence: "Give it to me please." },
    { word: "my",   hint: "Belonging to me",                sentence: "This is my book." },
    { word: "no",   hint: "The opposite of yes",            sentence: "No, I do not want any." },
    { word: "of",   hint: "Belonging to something",         sentence: "I drank a cup of milk." },
    { word: "on",   hint: "On top of something",            sentence: "The book is on the desk." },
    { word: "or",   hint: "Used to show a choice",          sentence: "Do you want cake or pie?" },
    { word: "so",   hint: "Showing a result",               sentence: "It was hot, so I drank water." },
    { word: "to",   hint: "Moving toward something",        sentence: "I walk to school." },
    { word: "up",   hint: "Toward a higher place",          sentence: "Look up at the sky!" },
    { word: "us",   hint: "Referring to me and others",     sentence: "She is with us today." },
    { word: "we",   hint: "Me and others together",         sentence: "We love to sing songs." },
    { word: "all",  hint: "Every single one",               sentence: "All my friends came." },
    { word: "and",  hint: "Connecting two things",          sentence: "I have cake and ice cream." },
    { word: "are",  hint: "A form of the word 'be'",        sentence: "You are very smart." },
    { word: "big",  hint: "Large in size",                  sentence: "That is a big elephant." },
    { word: "but",  hint: "Showing a difference",           sentence: "I like dogs but not cats." },
    { word: "can",  hint: "Able to do something",           sentence: "I can jump really high." },
    { word: "cat",  hint: "A furry pet that meows",         sentence: "The cat sat on the mat." },
    { word: "cup",  hint: "You drink from it",              sentence: "Fill the cup with water." },
    { word: "dad",  hint: "A word for your father",         sentence: "My dad makes breakfast." },
    { word: "did",  hint: "Past tense of do",               sentence: "What did you eat today?" },
    { word: "dog",  hint: "A furry pet that barks",         sentence: "The dog runs fast." },
    { word: "eat",  hint: "To put food in your mouth",      sentence: "I eat breakfast every morning." },
    { word: "for",  hint: "Used to show purpose",           sentence: "This gift is for you." },
    { word: "fun",  hint: "Something you enjoy",            sentence: "Reading books is fun!" },
    { word: "get",  hint: "To receive or fetch",            sentence: "Go get your coat." },
    { word: "got",  hint: "Past tense of get",              sentence: "I got a new pencil today." },
    { word: "had",  hint: "Past tense of have",             sentence: "She had a big birthday party." },
    { word: "has",  hint: "A form of have",                 sentence: "He has a red ball." },
    { word: "her",  hint: "Belonging to a girl",            sentence: "That is her purple hat." },
    { word: "him",  hint: "Referring to a boy",             sentence: "Give it to him." },
    { word: "his",  hint: "Belonging to a boy",             sentence: "His name is Sam." },
    { word: "hot",  hint: "Having a high temperature",      sentence: "Be careful, the soup is hot!" },
    { word: "let",  hint: "Allow something",                sentence: "Let me help you." },
    { word: "mom",  hint: "A word for your mother",         sentence: "My mom hugs me every day." },
    { word: "not",  hint: "Used to make things negative",   sentence: "I am not tired." },
    { word: "one",  hint: "The number 1",                   sentence: "I have one brother." },
    { word: "our",  hint: "Belonging to all of us",         sentence: "This is our classroom." },
    { word: "out",  hint: "Outside of something",           sentence: "The cat went out." },
    { word: "put",  hint: "To place something somewhere",   sentence: "Put your shoes away." },
    { word: "ran",  hint: "Past tense of run",              sentence: "She ran to the bus stop." },
    { word: "red",  hint: "A color like strawberries",      sentence: "I have a red jacket." },
    { word: "run",  hint: "To move fast on your feet",      sentence: "I love to run outside." },
    { word: "sat",  hint: "Past tense of sit",              sentence: "He sat next to me." },
    { word: "see",  hint: "To look at something",           sentence: "Can you see the rainbow?" },
    { word: "she",  hint: "A word for a girl or woman",     sentence: "She is my best friend." },
    { word: "sun",  hint: "The big bright star in the sky", sentence: "The sun is very bright today." },
    { word: "ten",  hint: "The number after nine",          sentence: "I count to ten." },
    { word: "the",  hint: "The most common English word",   sentence: "The sky is blue." },
    { word: "too",  hint: "Also; more than enough",         sentence: "I want to come too!" },
    { word: "top",  hint: "The highest part",               sentence: "I am at the top of the stairs." },
    { word: "two",  hint: "The number after one",           sentence: "I have two shoes." },
    { word: "was",  hint: "Past tense of 'is'",             sentence: "It was a great day." },
    { word: "why",  hint: "Asking for a reason",            sentence: "Why is the sky blue?" },
    { word: "yes",  hint: "Saying you agree",               sentence: "Yes, I finished my work!" },
    { word: "you",  hint: "The person being spoken to",     sentence: "I love you very much." },
    { word: "your", hint: "Belonging to you",               sentence: "Is this your seat?" },
  ],
};
export default gradeK;
