const grade7 = {
  grade: 7, roundSize: 14,
  pool: [
    { word: "aberration",       hint: "A departure from what is normal",            sentence: "His rude comment was an aberration — he is usually very kind." },
    { word: "acquiesce",        hint: "Accept something reluctantly but without protest", sentence: "She chose to acquiesce rather than argue further." },
    { word: "ambivalence",      hint: "Having mixed feelings about something",       sentence: "His ambivalence about the move made it hard to pack." },
    { word: "anachronism",      hint: "Something out of its proper time period",     sentence: "A knight using a smartphone would be a clear anachronism." },
    { word: "cacophony",        hint: "A harsh, discordant mixture of sounds",       sentence: "The cafeteria was filled with a cacophony of voices." },
    { word: "consternation",    hint: "Feelings of anxiety or dismay",               sentence: "The sudden change in plans caused great consternation." },
    { word: "corroborate",      hint: "Confirm or support with evidence",            sentence: "The second witness helped corroborate his story." },
    { word: "denounce",         hint: "Publicly declare to be wrong or evil",        sentence: "The community gathered to denounce the injustice." },
    { word: "desolate",         hint: "Deserted; lacking inhabitants; bleak",        sentence: "After the storm, the streets were completely desolate." },
    { word: "ephemeral",        hint: "Lasting for a very short time",               sentence: "Beauty is ephemeral, but character lasts forever." },
    { word: "exacerbate",       hint: "Make a problem or situation worse",           sentence: "Arguing only served to exacerbate the misunderstanding." },
    { word: "fortitude",        hint: "Courage in pain or adversity",                sentence: "She faced her illness with remarkable fortitude." },
    { word: "gregarious",       hint: "Fond of company; sociable",                   sentence: "He was gregarious by nature and knew everyone by name." },
    { word: "hypocritical",     hint: "Claiming beliefs one does not have",          sentence: "It is hypocritical to preach honesty while telling lies." },
    { word: "inconsequential",  hint: "Not important or significant",                sentence: "He dismissed the error as inconsequential." },
    { word: "nomenclature",     hint: "A system of names used in a field",           sentence: "Scientists use precise nomenclature to avoid confusion." },
    { word: "ostentatious",     hint: "Designed to impress; showy",                  sentence: "The ostentatious mansion was visible from across the lake." },
    { word: "precarious",       hint: "Not securely held; risky",                    sentence: "He held the glass in a precarious grip at the edge of the table." },
    { word: "superfluous",      hint: "Unnecessary; more than enough",               sentence: "The lengthy introduction was superfluous and could be cut." },
    { word: "vacillate",        hint: "Waver between different opinions",            sentence: "Don't vacillate — make a decision and stick with it." },
  ],
};
export default grade7;
