const grade1 = {
  grade: 1,
  roundSize: 8,
  pool: [
    { word: "the",  hint: "Most common word in English",     sentence: "The dog ran to the park." },
    { word: "and",  hint: "Connects two things together",    sentence: "I have a cat and a dog." },
    { word: "cat",  hint: "A furry pet that meows",          sentence: "The cat sat on the mat." },
    { word: "dog",  hint: "A furry pet that barks",          sentence: "My dog likes to play fetch." },
    { word: "big",  hint: "The opposite of small",           sentence: "That is a big red ball." },
    { word: "run",  hint: "Faster than walking",             sentence: "I run to school every day." },
    { word: "sun",  hint: "Lights up the daytime sky",       sentence: "The sun is bright today." },
    { word: "fun",  hint: "Means enjoyable",                 sentence: "We had so much fun at the park." },
    { word: "bat",  hint: "You use it in baseball",          sentence: "He hit the ball with his bat." },
    { word: "hat",  hint: "Worn on your head",               sentence: "She wore a red hat to the party." },
    { word: "mat",  hint: "You wipe your feet on it",        sentence: "Please wipe your feet on the mat." },
    { word: "sit",  hint: "What you do in a chair",          sentence: "Please sit down in your seat." },
    { word: "hot",  hint: "The opposite of cold",            sentence: "Be careful — the soup is very hot." },
    { word: "wet",  hint: "The opposite of dry",             sentence: "My shoes got wet in the rain." },
    { word: "red",  hint: "The color of an apple",           sentence: "She wore a beautiful red dress." },
    { word: "bed",  hint: "You sleep in it at night",        sentence: "I make my bed every morning." },
    { word: "boy",  hint: "A male child",                    sentence: "The young boy rode his bike." },
    { word: "girl", hint: "A female child",                  sentence: "The little girl wore a pink dress." },
    { word: "toy",  hint: "Something you play with",         sentence: "He shared his favorite toy with his brother." },
    { word: "man",  hint: "An adult male person",            sentence: "The tall man reached the top shelf." },
    { word: "play", hint: "To have fun doing something",     sentence: "We like to play games after dinner." },
    { word: "day",  hint: "When the sun is up",              sentence: "It is a beautiful sunny day." },
    { word: "say",  hint: "To speak words",                  sentence: "What did you say to me?" },
    { word: "may",  hint: "Asking for permission",           sentence: "May I please have a cookie?" },
    { word: "way",  hint: "A path or direction",             sentence: "Which way to the playground?" },
    { word: "see",  hint: "To look with your eyes",          sentence: "I can see the bird in the tree." },
    { word: "tree", hint: "A tall plant with a trunk and leaves", sentence: "The apples fell from the tree." },
    { word: "bee",  hint: "A flying insect that makes honey",sentence: "The bee landed on a flower." },
    { word: "look", hint: "To turn your eyes toward something", sentence: "Look at the stars in the sky!" },
    { word: "book", hint: "Pages with words and pictures to read", sentence: "I read a book before bed." },
    { word: "good", hint: "The opposite of bad",             sentence: "You did a good job on your homework." },
    { word: "foot", hint: "The body part you stand on",      sentence: "He stubbed his toe on his foot." },
    { word: "out",  hint: "The opposite of in",              sentence: "The cat wants to go out." },
    { word: "down", hint: "The opposite of up",              sentence: "Please sit down quietly." },
    { word: "now",  hint: "At this very moment",             sentence: "We need to leave right now." },
    { word: "how",  hint: "Asking the way to do something",  sentence: "How do you spell your name?" },
    { word: "cow",  hint: "A farm animal that gives milk",   sentence: "The cow eats grass in the field." },
    { word: "all",  hint: "Every single one",                sentence: "We ate all the pizza." },
    { word: "ball", hint: "A round object used in games",    sentence: "He threw the ball to his dog." },
    { word: "call", hint: "To shout or use a phone",         sentence: "I will call you on the phone later." },
  ],
};
export default grade1;
