const grade3 = {
  grade: 3, roundSize: 10,
  pool: [
    { word: "accept",    hint: "Agree to receive something",      sentence: "Please accept this gift with a smile." },
    { word: "answer",    hint: "A reply to a question",           sentence: "She raised her hand to answer the question." },
    { word: "believe",   hint: "Think something is true",         sentence: "I believe you can do anything you try." },
    { word: "breathe",   hint: "Take air in and out",             sentence: "Take a moment to breathe deeply and relax." },
    { word: "center",    hint: "The middle point",                sentence: "Put the flower vase in the center of the table." },
    { word: "change",    hint: "Become different",                sentence: "The leaves change color every fall." },
    { word: "complete",  hint: "Finish entirely; whole",          sentence: "Make sure you complete all your homework." },
    { word: "danger",    hint: "Risk of harm",                    sentence: "The sign warned of danger on the icy road." },
    { word: "decide",    hint: "Make a choice",                   sentence: "It was hard to decide which book to read first." },
    { word: "different", hint: "Not the same as others",          sentence: "Every snowflake is different from all the rest." },
    { word: "enough",    hint: "A sufficient amount",             sentence: "Do we have enough bread for everyone?" },
    { word: "explain",   hint: "Make something clear",            sentence: "Can you explain how fractions work?" },
    { word: "famous",    hint: "Known by many people",            sentence: "She became famous for her beautiful paintings." },
    { word: "finally",   hint: "At the end; at last",             sentence: "After hours of hiking, we finally reached the top." },
    { word: "forward",   hint: "In the direction ahead",          sentence: "Take two steps forward and one step back." },
    { word: "friend",    hint: "Someone you like and trust",      sentence: "A good friend is hard to find." },
    { word: "important", hint: "Of great value or significance",  sentence: "It is important to tell the truth." },
    { word: "pretty",    hint: "Attractive to look at",           sentence: "The garden looks pretty in the springtime." },
    { word: "remember",  hint: "Bring back to mind",              sentence: "Please remember to bring your library book." },
    { word: "surprise",  hint: "Something unexpected",            sentence: "The birthday party was a wonderful surprise." },
  ],
};
export default grade3;
