const grade4 = {
  grade: 4, roundSize: 12,
  pool: [
    { word: "achievement",  hint: "Something accomplished through effort",    sentence: "Finishing the race was a great achievement." },
    { word: "calendar",     hint: "Tool for tracking dates",                  sentence: "Check the calendar to find the date of the field trip." },
    { word: "conscience",   hint: "Inner sense of right and wrong",           sentence: "His conscience told him to return the lost wallet." },
    { word: "convenience",  hint: "Something that saves time or effort",      sentence: "The store nearby is a real convenience for our family." },
    { word: "describe",     hint: "Give details about something",             sentence: "Can you describe what the main character looks like?" },
    { word: "disappear",    hint: "Vanish from sight",                        sentence: "The magician made the rabbit disappear." },
    { word: "environment",  hint: "The natural world around us",              sentence: "We should all do our part to protect the environment." },
    { word: "exercise",     hint: "Physical activity for health",             sentence: "Daily exercise keeps your body strong and healthy." },
    { word: "experience",   hint: "Knowledge gained from doing things",       sentence: "Working at the bakery was a great experience." },
    { word: "foreign",      hint: "From another country",                     sentence: "She learned to speak a foreign language in one year." },
    { word: "government",   hint: "Group that rules a country",               sentence: "The government passed a new law to protect animals." },
    { word: "grateful",     hint: "Feeling thankful",                         sentence: "I am so grateful for my wonderful family." },
    { word: "guarantee",    hint: "A promise that something will happen",     sentence: "The store offers a guarantee on all their products." },
    { word: "independent",  hint: "Not relying on others",                    sentence: "She worked hard to become an independent reader." },
    { word: "necessary",    hint: "Cannot be done without",                   sentence: "It is necessary to drink water every single day." },
    { word: "occasion",     hint: "A special event or time",                  sentence: "A birthday is a very happy occasion." },
    { word: "particular",   hint: "Specific; detailed",                       sentence: "He was very particular about how he organized his desk." },
    { word: "permanent",    hint: "Lasting forever",                          sentence: "The scar on his knee was permanent." },
    { word: "privilege",    hint: "A special right or benefit",               sentence: "Going to a great school is a real privilege." },
    { word: "strength",     hint: "The quality of being strong",              sentence: "Prayer gives me strength when things are hard." },
    { word: "adventure",    hint: "An exciting or unusual experience",        sentence: "We went on an adventure through the woods." },
    { word: "afraid",       hint: "Feeling fear",                             sentence: "Are you afraid of the dark?" },
    { word: "airplane",     hint: "A vehicle with wings that flies",          sentence: "The airplane soared above the clouds." },
    { word: "almost",       hint: "Very nearly; not quite",                   sentence: "We are almost at grandmother's house." },
    { word: "already",      hint: "Before the time in question",              sentence: "I have already finished my homework." },
    { word: "although",     hint: "In spite of the fact that",                sentence: "She was smiling, although she felt sad." },
    { word: "amount",       hint: "A quantity of something",                  sentence: "What amount of flour do we need?" },
    { word: "angle",        hint: "The space between two intersecting lines", sentence: "The triangle has a sharp angle." },
    { word: "anger",        hint: "A strong feeling of annoyance",            sentence: "He spoke with a lot of anger in his voice." },
    { word: "appear",       hint: "To come into sight",                       sentence: "The stars appear when the sun sets." },
    { word: "arrive",       hint: "To reach a destination",                   sentence: "When will the train arrive at the station?" },
    { word: "article",      hint: "A piece of writing in a newspaper",        sentence: "I read an interesting article about space." },
    { word: "attack",       hint: "Take aggressive action against",           sentence: "The dog barked but did not attack." },
    { word: "attempt",      hint: "Make an effort to achieve or complete",    sentence: "He will attempt to climb the mountain." },
    { word: "beauty",       hint: "The quality of being very attractive",     sentence: "The beauty of the sunset took our breath away." },
    { word: "beyond",       hint: "At or to the further side of",             sentence: "The forest stretches beyond the river." },
    { word: "blanket",      hint: "A large piece of woolen material",         sentence: "I need an extra blanket because I am cold." },
    { word: "bottom",       hint: "The lowest point or part",                 sentence: "The toy sank to the bottom of the pool." },
    { word: "breath",       hint: "The air taken into or expelled from lungs",sentence: "Take a deep breath and calm down." },
    { word: "bright",       hint: "Giving out or reflecting a lot of light",  sentence: "The sun is very bright today." },
    { word: "broken",       hint: "Having been fractured or damaged",         sentence: "The glass fell and lay broken on the floor." },
    { word: "builder",      hint: "A person who constructs something",        sentence: "The builder wore a hard hat to work." },
    { word: "business",     hint: "A person's regular occupation",            sentence: "They run a small business selling toys." },
    { word: "button",       hint: "A small disk sewn to a garment",           sentence: "My coat is missing a button." },
    { word: "cabbage",      hint: "A leafy green vegetable",                  sentence: "We had cabbage stew for dinner." },
    { word: "camera",       hint: "A device for taking photographs",          sentence: "Say cheese and look at the camera!" },
    { word: "candle",       hint: "A block of wax containing a wick",         sentence: "She lit the candle on her birthday cake." },
    { word: "carefully",    hint: "In a way that avoids harm or errors",      sentence: "Please drive carefully in the rain." },
    { word: "carpet",       hint: "A floor covering made of thick fabric",    sentence: "We vacuumed the carpet until it was clean." },
    { word: "caught",       hint: "Past tense of catch",                      sentence: "He caught the ball right before it hit the ground." },
    { word: "ceiling",      hint: "The upper interior surface of a room",     sentence: "A spider was crawling on the ceiling." },
  ],
};
export default grade4;
