const grade8 = {
  grade: 8, roundSize: 15,
  pool: [
    { word: "abstinence",       hint: "Self-restraint from indulging a desire",        sentence: "Abstinence from social media improved her focus dramatically." },
    { word: "acrimony",         hint: "Bitterness or ill feeling",                     sentence: "The debate ended with acrimony on both sides." },
    { word: "anomalous",        hint: "Deviating from what is standard",               sentence: "The anomalous result prompted the scientists to repeat the test." },
    { word: "apprehension",     hint: "Anxiety or fear about a future event",          sentence: "She waited with apprehension for the judge's decision." },
    { word: "bellicose",        hint: "Demonstrating aggression; eager to fight",      sentence: "His bellicose attitude made every conversation a confrontation." },
    { word: "circumspect",      hint: "Wary and unwilling to take risks",              sentence: "A circumspect investor never puts all their money in one place." },
    { word: "cogent",           hint: "Clear, logical, and convincing",                sentence: "She made a cogent argument that convinced even the skeptics." },
    { word: "complacency",      hint: "Smug and uncritical self-satisfaction",         sentence: "Complacency after early success led to their eventual failure." },
    { word: "conscientious",    hint: "Wishing to do one's work thoroughly and well",  sentence: "A conscientious student checks their work before submitting." },
    { word: "disingenuous",     hint: "Not candid or sincere; insincere",              sentence: "His apology felt disingenuous because he never changed his behavior." },
    { word: "frivolous",        hint: "Not having any serious purpose",                sentence: "The judge dismissed the frivolous lawsuit immediately." },
    { word: "idiosyncratic",    hint: "Peculiar to the individual; quirky",            sentence: "His idiosyncratic teaching style made the class unforgettable." },
    { word: "immutable",        hint: "Unchanging over time or impossible to change",  sentence: "Certain natural laws are immutable and cannot be negotiated." },
    { word: "indignation",      hint: "Anger at something unjust or unfair",           sentence: "The crowd expressed their indignation at the unfair verdict." },
    { word: "malfeasance",      hint: "Wrongdoing, especially by a public official",   sentence: "The official resigned amid accusations of malfeasance in office." },
    { word: "meticulous",       hint: "Showing great attention to detail",             sentence: "The meticulous editor caught every error in the manuscript." },
    { word: "pedantic",         hint: "Overly concerned with minor, trivial details",  sentence: "His pedantic corrections annoyed the other team members." },
    { word: "prerogative",      hint: "A right or privilege belonging to a person",    sentence: "It is your prerogative to choose how you spend your free time." },
    { word: "truculent",        hint: "Eager or quick to argue or fight",              sentence: "The truculent child argued with every instruction given." },
    { word: "ubiquitous",       hint: "Present, appearing, or found everywhere",       sentence: "Smartphones are now ubiquitous in modern daily life." },
  ],
};
export default grade8;
