const grade5 = {
  grade: 5, roundSize: 12,
  pool: [
    { word: "abundance",      hint: "A very large amount of something",        sentence: "The garden produced an abundance of vegetables this year." },
    { word: "accomplishment",  hint: "A completed achievement",                sentence: "Learning to play piano was her greatest accomplishment." },
    { word: "anonymous",       hint: "Without a known name",                   sentence: "The generous donation was made by an anonymous person." },
    { word: "approximately",   hint: "Close to; roughly",                      sentence: "The drive takes approximately two hours." },
    { word: "circumstance",    hint: "A condition that affects a situation",   sentence: "Under no circumstance should you leave without telling me." },
    { word: "collaboration",   hint: "Working together with others",           sentence: "The project was a collaboration between three schools." },
    { word: "commemorate",     hint: "Honor the memory of something",          sentence: "The statue was built to commemorate fallen soldiers." },
    { word: "communicate",     hint: "Share information with others",          sentence: "It is important to communicate clearly and kindly." },
    { word: "comparison",      hint: "Examining similarities and differences", sentence: "The comparison showed that the new book is better." },
    { word: "consequence",     hint: "A result of an action",                  sentence: "Every choice has a consequence, good or bad." },
    { word: "curiosity",       hint: "Desire to know or learn",                sentence: "Her curiosity led her to read every book in the library." },
    { word: "definitely",      hint: "Without any doubt",                      sentence: "I will definitely be at your performance tonight." },
    { word: "demonstrate",     hint: "Show how something works",               sentence: "The teacher will demonstrate the science experiment first." },
    { word: "determination",   hint: "Firmly decided; persistence",            sentence: "With determination, he practiced every day until he won." },
    { word: "exaggerate",      hint: "Make something seem bigger than it is",  sentence: "Don't exaggerate — it wasn't that scary!" },
    { word: "fascinate",       hint: "Hold someone's interest strongly",       sentence: "The documentary about oceans never failed to fascinate me." },
    { word: "knowledge",       hint: "Facts and understanding gained",         sentence: "Reading builds knowledge that stays with you forever." },
    { word: "punctuation",     hint: "Marks used in writing like commas",      sentence: "Correct punctuation makes your writing much easier to read." },
    { word: "significant",     hint: "Important or meaningful",                sentence: "The discovery was a significant moment in science." },
    { word: "transparent",     hint: "Able to be seen through; open",          sentence: "Good leaders are transparent about their decisions." },
  ],
};
export default grade5;
