const grade6 = {
  grade: 6, roundSize: 14,
  pool: [
    { word: "acknowledge",    hint: "Accept or admit the truth of",           sentence: "He was quick to acknowledge his mistake." },
    { word: "ambiguous",      hint: "Open to more than one interpretation",   sentence: "The ending of the story was deliberately ambiguous." },
    { word: "assertive",      hint: "Confident and direct in manner",         sentence: "Being assertive does not mean being rude." },
    { word: "benevolent",     hint: "Well-meaning and kind",                  sentence: "The benevolent woman donated food to every family on the street." },
    { word: "chronological",  hint: "Arranged in order of time",              sentence: "Put the events in chronological order starting with the earliest." },
    { word: "controversial",  hint: "Causing strong disagreement",             sentence: "It was a controversial decision that divided the community." },
    { word: "deteriorate",    hint: "Become progressively worse",             sentence: "The old building began to deteriorate after years of neglect." },
    { word: "diligent",       hint: "Having steady, careful effort",          sentence: "She was a diligent student who never missed an assignment." },
    { word: "discrepancy",    hint: "A difference between things that should match", sentence: "There was a discrepancy between what he said and what he did." },
    { word: "eloquent",       hint: "Fluent or persuasive in speech",         sentence: "Her eloquent speech moved the entire audience to tears." },
    { word: "equilibrium",    hint: "A state of balance",                     sentence: "After the earthquake, the town slowly returned to equilibrium." },
    { word: "hypothesis",     hint: "A proposed explanation to be tested",    sentence: "Her hypothesis was that plants grow faster with music." },
    { word: "impartial",      hint: "Treating all equally; unbiased",         sentence: "A judge must always be impartial and fair." },
    { word: "inevitable",     hint: "Certain to happen; unavoidable",         sentence: "Change is inevitable, so we must learn to embrace it." },
    { word: "magnificent",    hint: "Impressively beautiful or elaborate",    sentence: "The view from the mountain top was absolutely magnificent." },
    { word: "melancholy",     hint: "A deep feeling of sadness",              sentence: "A feeling of melancholy fell over him as summer ended." },
    { word: "perseverance",   hint: "Continued effort despite difficulty",    sentence: "Her perseverance through hardship inspired everyone around her." },
    { word: "preliminary",    hint: "Preceding or done before the main thing",sentence: "The preliminary results looked very promising." },
    { word: "relinquish",     hint: "Voluntarily give up something",          sentence: "She had to relinquish her title after moving away." },
    { word: "unprecedented",  hint: "Never done or known before",             sentence: "The flood was unprecedented in the town's recorded history." },
    { word: "abundant",       hint: "Existing or available in large quantities; plentiful", sentence: "The land was full of an abundant supply of fresh water." },
    { word: "accessible",     hint: "Able to be reached or entered",          sentence: "The building was made fully accessible for all students." },
    { word: "accommodate",    hint: "Provide lodging or sufficient space for",sentence: "The hotel can accommodate up to five hundred guests." },
    { word: "adequately",     hint: "To a satisfactory or acceptable extent", sentence: "Make sure you are adequately prepared for the hike." },
    { word: "adolescence",    hint: "The period following the onset of puberty",sentence: "During adolescence, young people go through many changes." },
    { word: "advantageous",   hint: "Involving or creating favorable circumstances", sentence: "Moving during the summer was highly advantageous." },
    { word: "aggressive",     hint: "Ready or likely to attack or confront",  sentence: "The aggressive dog had to be kept behind a fence." },
    { word: "algorithm",      hint: "A process or set of rules to be followed",sentence: "The computer used a complex algorithm to sort the data." },
    { word: "alternative",    hint: "One of two or more available possibilities", sentence: "We had to find an alternative route due to the closed road." },
    { word: "amateur",        hint: "A person who engages in a pursuit on an unpaid basis", sentence: "The tournament was open to amateur golfers only." },
    { word: "apparatus",      hint: "The technical equipment or machinery",   sentence: "The scientists carefully built a new experimental apparatus." },
    { word: "apparently",     hint: "As far as one knows or can see",         sentence: "Apparently, the store is closed on Sundays." },
    { word: "approximate",    hint: "Close to the actual, but not completely accurate", sentence: "Can you give me an approximate cost for the repair?" },
    { word: "arrogant",       hint: "Having an exaggerated sense of one's own importance", sentence: "His arrogant attitude made him unpopular among his peers." },
    { word: "artificial",     hint: "Made or produced by human beings",       sentence: "The flowers in the vase were completely artificial." },
    { word: "assessment",     hint: "The evaluation or estimation of the nature", sentence: "They conducted a thorough assessment of the damage." },
    { word: "association",    hint: "A group of people organized for a joint purpose", sentence: "He joined a neighborhood association to help clean parks." },
    { word: "atmosphere",     hint: "The envelope of gases surrounding the earth", sentence: "Meteorologists study the Earth's atmosphere." },
    { word: "authentic",      hint: "Of undisputed origin; genuine",          sentence: "The restaurant serves authentic Italian pizza." },
    { word: "authority",      hint: "The power or right to give orders",      sentence: "The supervisor has the authority to approve vacation time." },
    { word: "automatic",      hint: "Working by itself with little or no direct human control", sentence: "The automatic doors opened as we approached the store." },
    { word: "basically",      hint: "In the most fundamental respects",       sentence: "Basically, we need to start the project from scratch." },
    { word: "beneficial",     hint: "Favorable or advantageous",              sentence: "Eating vegetables is beneficial to your health." },
    { word: "bibliography",   hint: "A list of the books referred to in a scholarly work", sentence: "Don't forget to include a bibliography at the end of your paper." },
    { word: "boundary",       hint: "A line that marks the limits of an area",sentence: "A large fence formed the boundary of the property." },
    { word: "brigade",        hint: "A subdivision of an army",               sentence: "The fire brigade arrived quickly to put out the blaze." },
    { word: "catastrophe",    hint: "An event causing great and often sudden damage", sentence: "The hurricane was a terrible catastrophe for the coastal town." },
    { word: "ceremony",       hint: "A formal religious or public occasion",  sentence: "We attended the awards ceremony in the auditorium." },
    { word: "challenge",      hint: "A task or situation that tests someone's abilities", sentence: "Running the marathon was an incredible challenge." },
    { word: "circumstantial", hint: "Pointing indirectly to a conclusion",       sentence: "The evidence was circumstantial, not definitive." },
    { word: "civilization",   hint: "An advanced state of human society",        sentence: "Ancient Egypt was one of history's greatest civilizations." },
    { word: "collaborate",    hint: "Work jointly on an activity",               sentence: "The students collaborated on the group science project." },
    { word: "commemorate",    hint: "Recall and show respect for someone/event", sentence: "We gathered to commemorate the anniversary of the founding." },
    { word: "commentary",     hint: "Explanatory or critical notes on a text",   sentence: "The sports commentary kept fans informed all game." },
    { word: "commisserate",   hint: "Express sympathy for another's misfortune", sentence: "Her friends came over to commisserate after the loss." },
    { word: "communicate",    hint: "Share or exchange information",             sentence: "It is vital to communicate clearly in teamwork." },
    { word: "competence",     hint: "The ability to do something efficiently",   sentence: "The surgeon's level of competence was unquestionable." },
    { word: "comprehension",  hint: "The ability to understand something",       sentence: "Reading comprehension improves with daily practice." },
    { word: "conspicuous",    hint: "Attracting notice or attention",            sentence: "His bright red jacket was conspicuous in the crowd." },
    { word: "contaminate",    hint: "Make impure by exposure to a substance",    sentence: "The oil spill contaminated miles of coastline." },
    { word: "conventional",   hint: "Based on what is generally done; standard", sentence: "His conventional approach to art did not impress critics." },
    { word: "convergence",    hint: "The process of coming together",            sentence: "The convergence of two rivers created a wide lake." },
    { word: "convey",         hint: "To communicate or make known",              sentence: "The painting conveys a sense of great sadness." },
    { word: "cooperate",      hint: "Work together toward the same end",         sentence: "The two departments must cooperate to finish this project." },
    { word: "corruption",     hint: "Dishonest or fraudulent conduct",           sentence: "Corruption in government undermines public trust." },
    { word: "credibility",    hint: "The quality of being trusted or believed",  sentence: "The witness's credibility was vital to the court case." },
    { word: "criticism",      hint: "The expression of disapproval or judgment", sentence: "She took the criticism gracefully and improved her work." },
    { word: "cryptic",        hint: "Having a meaning that is mysterious",       sentence: "He left a cryptic message no one could decode." },
    { word: "cultivate",      hint: "To develop or improve something",           sentence: "A good teacher helps cultivate a love of learning." },
    { word: "customary",      hint: "In accordance with custom; usual",          sentence: "It is customary to shake hands when greeting someone new." },
    { word: "cynical",        hint: "Distrustful of human sincerity or integrity", sentence: "Years of setbacks had made him cynical about promises." },
    { word: "declaration",    hint: "A formal announcement",                     sentence: "The declaration of independence was a turning point in history." },
    { word: "degrade",        hint: "Treat or regard with contempt; deteriorate",sentence: "Pollution continues to degrade our water supply." },
    { word: "deliberate",     hint: "Done consciously and intentionally",        sentence: "The deliberate choice to be honest paid off in the end." },
    { word: "democracy",      hint: "A system of government by the whole population", sentence: "We are grateful to live in a democracy." },
    { word: "despondency",    hint: "A state of low spirits caused by loss of hope", sentence: "Despondency set in after the team kept losing." },
    { word: "determine",      hint: "Cause a particular outcome",               sentence: "Your effort will determine your level of success." },
    { word: "devastate",      hint: "Destroy or ruin something",                 sentence: "The earthquake devastated entire neighborhoods." },
    { word: "differentiate",  hint: "Recognize as different; distinguish",      sentence: "Can you differentiate between a simile and a metaphor?" },
    { word: "diminish",       hint: "Make or become less",                       sentence: "The noise slowly began to diminish as the crowd left." },
    { word: "disillusion",    hint: "Cause to feel disappointed",               sentence: "The defeat seemed to disillusion the entire fanbase." },
    { word: "distinguish",    hint: "Recognize as being different",             sentence: "How do you distinguish between a crocodile and an alligator?" },
    { word: "diverse",        hint: "Showing a great variety; varied",           sentence: "Our school community is wonderfully diverse." },
    { word: "documentation",  hint: "Material providing official information",   sentence: "Submit all documentation before the deadline." },
    { word: "domination",     hint: "Power and influence over others",           sentence: "The empire's domination extended across three continents." },
    { word: "dramatize",      hint: "Represent in a theatrical or dramatic form",sentence: "The students chose to dramatize the folk tale." },
    { word: "duplicate",      hint: "Make an exact copy of something",           sentence: "Please duplicate the form for your records." },
    { word: "elaborate",      hint: "Develop or explain in detail",              sentence: "Could you elaborate on what you mean by 'complex'?" },
    { word: "eloquence",      hint: "The ability to speak fluently and persuasively", sentence: "Her eloquence in debate class left everyone impressed." },
    { word: "emancipate",     hint: "Set free from legal or social restraints",  sentence: "Lincoln acted to emancipate enslaved people in America." },
    { word: "embellish",      hint: "Make more attractive by adding details",    sentence: "She liked to embellish her stories a little." },
    { word: "empathy",        hint: "The ability to understand another's feelings", sentence: "Empathy is one of the most important human traits." },
    { word: "endeavor",       hint: "Try hard to achieve something",             sentence: "We will endeavor to complete the project on time." },
    { word: "enthusiasm",     hint: "Intense and eager enjoyment",               sentence: "She approached every class with incredible enthusiasm." },
    { word: "environment",    hint: "The natural world around us",               sentence: "We must all work together to protect our environment." },
    { word: "epidemic",       hint: "A widespread outbreak of a disease",        sentence: "The city worked hard to control the epidemic." },
    { word: "equality",       hint: "The state of being equal in rights",        sentence: "She fought her whole life for equality." },
    { word: "evolution",      hint: "The gradual development of something",      sentence: "The evolution of smartphones changed how we communicate." },
  ],
};
export default grade6;
