const grade4 = {
  grade: 4, roundSize: 12,
  pool: [
    { word: "achievement",  hint: "Something accomplished through effort",    sentence: "Finishing the race was a great achievement." },
    { word: "calendar",     hint: "Tool for tracking dates",                  sentence: "Check the calendar to find the date of the field trip." },
    { word: "conscience",   hint: "Inner sense of right and wrong",           sentence: "His conscience told him to return the lost wallet." },
    { word: "convenience",  hint: "Something that saves time or effort",      sentence: "The store nearby is a real convenience for our family." },
    { word: "describe",     hint: "Give details about something",             sentence: "Can you describe what the main character looks like?" },
    { word: "disappear",    hint: "Vanish from sight",                        sentence: "The magician made the rabbit disappear." },
    { word: "environment",  hint: "The natural world around us",              sentence: "We should all do our part to protect the environment." },
    { word: "exercise",     hint: "Physical activity for health",             sentence: "Daily exercise keeps your body strong and healthy." },
    { word: "experience",   hint: "Knowledge gained from doing things",       sentence: "Working at the bakery was a great experience." },
    { word: "foreign",      hint: "From another country",                     sentence: "She learned to speak a foreign language in one year." },
    { word: "government",   hint: "Group that rules a country",               sentence: "The government passed a new law to protect animals." },
    { word: "grateful",     hint: "Feeling thankful",                         sentence: "I am so grateful for my wonderful family." },
    { word: "guarantee",    hint: "A promise that something will happen",     sentence: "The store offers a guarantee on all their products." },
    { word: "independent",  hint: "Not relying on others",                    sentence: "She worked hard to become an independent reader." },
    { word: "necessary",    hint: "Cannot be done without",                   sentence: "It is necessary to drink water every single day." },
    { word: "occasion",     hint: "A special event or time",                  sentence: "A birthday is a very happy occasion." },
    { word: "particular",   hint: "Specific; detailed",                       sentence: "He was very particular about how he organized his desk." },
    { word: "permanent",    hint: "Lasting forever",                          sentence: "The scar on his knee was permanent." },
    { word: "privilege",    hint: "A special right or benefit",               sentence: "Going to a great school is a real privilege." },
    { word: "strength",     hint: "The quality of being strong",              sentence: "Prayer gives me strength when things are hard." },
    { word: "adventure",    hint: "An exciting or unusual experience",        sentence: "We went on an adventure through the woods." },
    { word: "afraid",       hint: "Feeling fear",                             sentence: "Are you afraid of the dark?" },
    { word: "airplane",     hint: "A vehicle with wings that flies",          sentence: "The airplane soared above the clouds." },
    { word: "almost",       hint: "Very nearly; not quite",                   sentence: "We are almost at grandmother's house." },
    { word: "already",      hint: "Before the time in question",              sentence: "I have already finished my homework." },
    { word: "although",     hint: "In spite of the fact that",                sentence: "She was smiling, although she felt sad." },
    { word: "amount",       hint: "A quantity of something",                  sentence: "What amount of flour do we need?" },
    { word: "angle",        hint: "The space between two intersecting lines", sentence: "The triangle has a sharp angle." },
    { word: "anger",        hint: "A strong feeling of annoyance",            sentence: "He spoke with a lot of anger in his voice." },
    { word: "appear",       hint: "To come into sight",                       sentence: "The stars appear when the sun sets." },
    { word: "arrive",       hint: "To reach a destination",                   sentence: "When will the train arrive at the station?" },
    { word: "article",      hint: "A piece of writing in a newspaper",        sentence: "I read an interesting article about space." },
    { word: "attack",       hint: "Take aggressive action against",           sentence: "The dog barked but did not attack." },
    { word: "attempt",      hint: "Make an effort to achieve or complete",    sentence: "He will attempt to climb the mountain." },
    { word: "beauty",       hint: "The quality of being very attractive",     sentence: "The beauty of the sunset took our breath away." },
    { word: "beyond",       hint: "At or to the further side of",             sentence: "The forest stretches beyond the river." },
    { word: "blanket",      hint: "A large piece of woolen material",         sentence: "I need an extra blanket because I am cold." },
    { word: "bottom",       hint: "The lowest point or part",                 sentence: "The toy sank to the bottom of the pool." },
    { word: "breath",       hint: "The air taken into or expelled from lungs",sentence: "Take a deep breath and calm down." },
    { word: "bright",       hint: "Giving out or reflecting a lot of light",  sentence: "The sun is very bright today." },
    { word: "broken",       hint: "Having been fractured or damaged",         sentence: "The glass fell and lay broken on the floor." },
    { word: "builder",      hint: "A person who constructs something",        sentence: "The builder wore a hard hat to work." },
    { word: "business",     hint: "A person's regular occupation",            sentence: "They run a small business selling toys." },
    { word: "button",       hint: "A small disk sewn to a garment",           sentence: "My coat is missing a button." },
    { word: "cabbage",      hint: "A leafy green vegetable",                  sentence: "We had cabbage stew for dinner." },
    { word: "camera",       hint: "A device for taking photographs",          sentence: "Say cheese and look at the camera!" },
    { word: "candle",       hint: "A block of wax containing a wick",         sentence: "She lit the candle on her birthday cake." },
    { word: "carefully",    hint: "In a way that avoids harm or errors",      sentence: "Please drive carefully in the rain." },
    { word: "carpet",       hint: "A floor covering made of thick fabric",    sentence: "We vacuumed the carpet until it was clean." },
    { word: "caught",       hint: "Past tense of catch",                      sentence: "He caught the ball right before it hit the ground." },
    { word: "ceiling",      hint: "The upper interior surface of a room",     sentence: "A spider was crawling on the ceiling." },
    { word: "champion",     hint: "A winner of a competition",                 sentence: "She is the reigning spelling champion." },
    { word: "character",    hint: "The mental and moral qualities of an individual", sentence: "Great character is more valuable than talent." },
    { word: "citizen",      hint: "A legal member of a country",               sentence: "Every citizen has the right to vote." },
    { word: "classify",     hint: "Arrange in groups by category",             sentence: "Scientists classify animals by their traits." },
    { word: "clever",       hint: "Quick to understand and learn",             sentence: "The clever student solved the puzzle in seconds." },
    { word: "climate",      hint: "The long-term weather of an area",          sentence: "The climate in Florida is warm and humid." },
    { word: "collect",      hint: "Gather things together",                    sentence: "I collect coins from around the world." },
    { word: "column",       hint: "A tall vertical support; also a row in a table", sentence: "Add the numbers in the right column." },
    { word: "combine",      hint: "Merge two or more things",                  sentence: "Combine the flour and sugar in a bowl." },
    { word: "compute",      hint: "Do mathematical calculations",              sentence: "I can compute the answer quickly in my head." },
    { word: "conflict",     hint: "A serious disagreement",                    sentence: "They resolved the conflict with kindness." },
    { word: "congress",     hint: "The national legislative body",             sentence: "Congress voted on the new education bill." },
    { word: "contain",      hint: "Hold or be able to hold something",         sentence: "The bowl can contain a lot of soup." },
    { word: "continent",    hint: "One of the seven large landmasses on Earth",sentence: "Africa is the world's second-largest continent." },
    { word: "contrast",     hint: "Compare to show differences",               sentence: "The artist used contrast to make the painting powerful." },
    { word: "council",      hint: "A group of advisors or leaders",            sentence: "The school council meets every Wednesday." },
    { word: "courage",      hint: "The ability to do something despite fear",  sentence: "It takes courage to stand up for what is right." },
    { word: "creature",     hint: "An animal or living being",                 sentence: "The creature in the book was a friendly dragon." },
    { word: "culture",      hint: "Shared ideas and traditions of a group",    sentence: "Each country has its own unique culture." },
    { word: "curious",      hint: "Eager to know or learn",                    sentence: "The curious student asked twenty questions." },
    { word: "current",      hint: "Happening now; also water movement",        sentence: "The current news story is about science." },
    { word: "custom",       hint: "A traditional way of doing something",      sentence: "It is a custom to share a meal on holidays." },
    { word: "damage",       hint: "Physical harm that makes something worse",  sentence: "The storm caused serious damage to the roof." },
    { word: "decade",       hint: "A period of ten years",                     sentence: "I have lived here for more than a decade." },
    { word: "declare",      hint: "Make a formal statement",                   sentence: "The president declared a national holiday." },
    { word: "definite",     hint: "Clearly established or stated",             sentence: "Is there a definite plan for the weekend?" },
    { word: "demand",       hint: "An insistent request",                      sentence: "I demand a fair and honest answer." },
    { word: "deposit",      hint: "Put money into a bank",                     sentence: "She went to deposit her paycheck." },
    { word: "develop",      hint: "Grow or make more advanced",                sentence: "Scientists develop new medicines every year." },
    { word: "diagram",      hint: "A drawing that explains something",         sentence: "Label each part of the diagram carefully." },
    { word: "difficult",    hint: "Not easy; requiring hard work",             sentence: "The test was difficult but fair." },
    { word: "discover",     hint: "Find something for the first time",         sentence: "Columbus attempted to discover a new route to Asia." },
    { word: "disease",      hint: "An illness affecting the body or mind",     sentence: "The doctor worked to cure the rare disease." },
    { word: "distance",     hint: "The amount of space between two places",    sentence: "The runner trained for the long distance race." },
    { word: "divide",       hint: "Separate into smaller parts",               sentence: "We divide the pizza between four friends." },
    { word: "document",     hint: "An official written paper",                 sentence: "She signed the important document." },
    { word: "dolphin",      hint: "A smart, playful ocean mammal",             sentence: "The dolphin leaped out of the water." },
    { word: "drought",      hint: "A long period without rain",                sentence: "The drought damaged crops all summer." },
    { word: "economy",      hint: "The system of money and trade",             sentence: "A strong economy helps people find jobs." },
    { word: "educate",      hint: "Give knowledge and instruction to",         sentence: "Parents and teachers educate children together." },
    { word: "effort",       hint: "The energy put into doing something",       sentence: "Her best effort earned her an A on the project." },
    { word: "element",      hint: "A fundamental part or substance",           sentence: "Gold is an element on the periodic table." },
    { word: "energy",       hint: "Power to do work",                         sentence: "Solar energy comes from the sun." },
    { word: "entire",       hint: "The full amount; complete",                 sentence: "She read the entire book in one day." },
    { word: "entrance",     hint: "The way into a building",                   sentence: "Please use the front entrance." },
    { word: "escape",       hint: "Break free from confinement",               sentence: "The rabbit managed to escape from the cage." },
    { word: "evidence",     hint: "Available facts indicating a truth",        sentence: "The detective collected evidence at the scene." },
    { word: "example",      hint: "A thing that illustrates a rule",           sentence: "Can you give me an example of a noun?" },
    { word: "expert",       hint: "A person with great skill or knowledge",    sentence: "She is an expert at playing the violin." },
    { word: "explore",      hint: "Travel through an unfamiliar area",         sentence: "We explored every corner of the museum." },
  ],
};
export default grade4;
