const grade10 = {
  grade: 10,
  roundSize: 15,
  pool: [
    { word: "abstruse",       hint: "Difficult to understand; obscure",           sentence: "The philosopher's argument was so abstruse that few could follow it." },
    { word: "acerbic",        hint: "Sharp and forthright; bitter in tone",       sentence: "Her acerbic wit could cut through any pretense in the room." },
    { word: "acrimony",       hint: "Bitterness or ill feeling in speech",        sentence: "The debate ended with great acrimony on both sides." },
    { word: "amalgamate",     hint: "Combine or unite to form one",               sentence: "The two companies decided to amalgamate to increase profits." },
    { word: "ameliorate",     hint: "Make something bad or unsatisfactory better",sentence: "New policies were enacted to ameliorate working conditions." },
    { word: "anachronistic",  hint: "Belonging to a period other than the present",sentence: "Using a typewriter in a modern office seemed wholly anachronistic." },
    { word: "antipathy",      hint: "A deep-seated feeling of aversion",          sentence: "She felt an immediate antipathy toward dishonest people." },
    { word: "apothegm",       hint: "A short witty instructive saying",           sentence: "His apothegm was quoted in every speech at the convention." },
    { word: "approbation",    hint: "Approval or praise",                         sentence: "The young writer beamed with joy upon receiving her mentor's approbation." },
    { word: "archetype",      hint: "A typical or original example of something", sentence: "Robin Hood is the archetype of the noble outlaw." },
    { word: "assiduity",      hint: "Constant or close attention to what one does",sentence: "His assiduity in studying paid off when he aced the exam." },
    { word: "atrophy",        hint: "Waste away due to lack of use",              sentence: "Muscles will atrophy if not used regularly." },
    { word: "audacity",       hint: "Willingness to take bold risks",             sentence: "She had the audacity to challenge the professor's theory publicly." },
    { word: "austerity",      hint: "Conditions of reduced comfort; sternness",   sentence: "The country endured years of economic austerity." },
    { word: "axiom",          hint: "A statement regarded as self-evidently true",sentence: "It is a mathematical axiom that parallel lines never meet." },
    { word: "baleful",        hint: "Threatening harm; menacing",                 sentence: "The dragon cast a baleful glare upon the approaching knight." },
    { word: "bathetic",       hint: "Producing an effect of anticlimax",          sentence: "The movie's ending was bathetic after two hours of intense drama." },
    { word: "bellicose",      hint: "Demonstrating aggression; eager to fight",   sentence: "The bellicose general prepared for war at every turn." },
    { word: "bemoan",         hint: "Express discontent or sorrow over",          sentence: "He would bemoan the state of the economy every morning." },
    { word: "bifurcate",      hint: "Divide into two branches or forks",          sentence: "The road bifurcates at the foot of the mountain." },
    { word: "blandishment",   hint: "Flattery or persuasion to do something",     sentence: "Her blandishments could not convince him to change his vote." },
    { word: "bombastic",      hint: "High-sounding language with little meaning", sentence: "The bombastic speech was all style and no substance." },
    { word: "brazen",         hint: "Bold and without shame",                     sentence: "The brazen thief stole the painting in broad daylight." },
    { word: "burgeon",        hint: "Begin to grow or increase rapidly",          sentence: "Interest in the new technology began to burgeon overnight." },
    { word: "byzantine",      hint: "Excessively complicated; intricate",         sentence: "The byzantine tax code confounded even the accountants." },
    { word: "calumny",        hint: "The making of false statements to damage reputation", sentence: "He sued the newspaper for publishing calumny about his career." },
    { word: "candor",         hint: "The quality of being open and honest",       sentence: "She spoke with candor about the struggles of her early life." },
    { word: "capitulate",     hint: "Cease to resist; surrender",                 sentence: "Faced with overwhelming evidence, she finally capitulated." },
    { word: "capriciousness", hint: "Sudden changes of behavior or attitude",     sentence: "His capriciousness made long-term planning nearly impossible." },
    { word: "catharsis",      hint: "The release of pent-up emotion",             sentence: "Writing poetry was a catharsis after all she had been through." },
    { word: "caustic",        hint: "Sarcastic in a scathing way",                sentence: "His caustic review of the book made the author furious." },
    { word: "censure",        hint: "Express severe disapproval of",              sentence: "The council chose to formally censure the member's conduct." },
    { word: "chicanery",      hint: "The use of trickery to achieve a goal",      sentence: "The deal was filled with chicanery that deceived investors." },
    { word: "circumspect",    hint: "Wary and unwilling to take risks",           sentence: "A circumspect investor always researches before committing." },
    { word: "clandestine",    hint: "Done in a secretive way; hidden",            sentence: "They held clandestine meetings in the basement after hours." },
    { word: "cogent",         hint: "Clear, logical, and convincing",             sentence: "The attorney made a cogent closing argument that swayed the jury." },
    { word: "complacency",    hint: "Uncritical self-satisfaction; smugness",     sentence: "Complacency after early success led to their ultimate failure." },
    { word: "compunction",    hint: "A feeling of guilt or moral scruple",        sentence: "He agreed to lie without the slightest compunction." },
    { word: "confound",       hint: "Cause surprise or confusion in",             sentence: "The magician's trick continued to confound the audience." },
    { word: "convoluted",     hint: "Extremely complex and difficult to follow",  sentence: "The convoluted plot lost most of the audience by the third act." },
    { word: "credulous",      hint: "Having too ready a belief in others",        sentence: "The credulous child believed every tall tale the peddler told." },
    { word: "decorous",       hint: "Characterized by good taste; dignified",     sentence: "The ceremony was decorous and appropriately solemn." },
    { word: "deferential",    hint: "Showing deference; respectful",              sentence: "Attendants were deferential to every guest's wishes." },
    { word: "demagogue",      hint: "A political leader who appeals to populist desires", sentence: "The demagogue exploited the people's fears for political gain." },
    { word: "denigrate",      hint: "Criticize unfairly; disparage",              sentence: "Stop trying to denigrate her accomplishments out of jealousy." },
    { word: "derivative",     hint: "Based on another source; lacking originality", sentence: "Critics found the film to be bland and derivative." },
    { word: "despondent",     hint: "In low spirits from loss of hope",           sentence: "After failing the exam twice, he grew despondent." },
    { word: "dichotomy",      hint: "A division into two opposite groups",        sentence: "There is a stark dichotomy between wealth and poverty in the city." },
    { word: "diffidence",     hint: "Modesty or shyness resulting from lack of confidence", sentence: "Her diffidence made it hard for her to speak up in class." },
    { word: "disingenuous",   hint: "Not candid or sincere; pretending naivete",  sentence: "His disingenuous apology convinced nobody who knew him." },
  ],
};
export default grade10;
