const grade6 = {
  grade: 6, roundSize: 14,
  pool: [
    { word: "acknowledge",    hint: "Accept or admit the truth of",           sentence: "He was quick to acknowledge his mistake." },
    { word: "ambiguous",      hint: "Open to more than one interpretation",   sentence: "The ending of the story was deliberately ambiguous." },
    { word: "assertive",      hint: "Confident and direct in manner",         sentence: "Being assertive does not mean being rude." },
    { word: "benevolent",     hint: "Well-meaning and kind",                  sentence: "The benevolent woman donated food to every family on the street." },
    { word: "chronological",  hint: "Arranged in order of time",              sentence: "Put the events in chronological order starting with the earliest." },
    { word: "controversial",  hint: "Causing strong disagreement",             sentence: "It was a controversial decision that divided the community." },
    { word: "deteriorate",    hint: "Become progressively worse",             sentence: "The old building began to deteriorate after years of neglect." },
    { word: "diligent",       hint: "Having steady, careful effort",          sentence: "She was a diligent student who never missed an assignment." },
    { word: "discrepancy",    hint: "A difference between things that should match", sentence: "There was a discrepancy between what he said and what he did." },
    { word: "eloquent",       hint: "Fluent or persuasive in speech",         sentence: "Her eloquent speech moved the entire audience to tears." },
    { word: "equilibrium",    hint: "A state of balance",                     sentence: "After the earthquake, the town slowly returned to equilibrium." },
    { word: "hypothesis",     hint: "A proposed explanation to be tested",    sentence: "Her hypothesis was that plants grow faster with music." },
    { word: "impartial",      hint: "Treating all equally; unbiased",         sentence: "A judge must always be impartial and fair." },
    { word: "inevitable",     hint: "Certain to happen; unavoidable",         sentence: "Change is inevitable, so we must learn to embrace it." },
    { word: "magnificent",    hint: "Impressively beautiful or elaborate",    sentence: "The view from the mountain top was absolutely magnificent." },
    { word: "melancholy",     hint: "A deep feeling of sadness",              sentence: "A feeling of melancholy fell over him as summer ended." },
    { word: "perseverance",   hint: "Continued effort despite difficulty",    sentence: "Her perseverance through hardship inspired everyone around her." },
    { word: "preliminary",    hint: "Preceding or done before the main thing",sentence: "The preliminary results looked very promising." },
    { word: "relinquish",     hint: "Voluntarily give up something",          sentence: "She had to relinquish her title after moving away." },
    { word: "unprecedented",  hint: "Never done or known before",             sentence: "The flood was unprecedented in the town's recorded history." },
  ],
};
export default grade6;
