const grade5 = {
  grade: 5, roundSize: 12,
  pool: [
    { word: "abundance",      hint: "A very large amount of something",        sentence: "The garden produced an abundance of vegetables this year." },
    { word: "accomplishment",  hint: "A completed achievement",                sentence: "Learning to play piano was her greatest accomplishment." },
    { word: "anonymous",       hint: "Without a known name",                   sentence: "The generous donation was made by an anonymous person." },
    { word: "approximately",   hint: "Close to; roughly",                      sentence: "The drive takes approximately two hours." },
    { word: "circumstance",    hint: "A condition that affects a situation",   sentence: "Under no circumstance should you leave without telling me." },
    { word: "collaboration",   hint: "Working together with others",           sentence: "The project was a collaboration between three schools." },
    { word: "commemorate",     hint: "Honor the memory of something",          sentence: "The statue was built to commemorate fallen soldiers." },
    { word: "communicate",     hint: "Share information with others",          sentence: "It is important to communicate clearly and kindly." },
    { word: "comparison",      hint: "Examining similarities and differences", sentence: "The comparison showed that the new book is better." },
    { word: "consequence",     hint: "A result of an action",                  sentence: "Every choice has a consequence, good or bad." },
    { word: "curiosity",       hint: "Desire to know or learn",                sentence: "Her curiosity led her to read every book in the library." },
    { word: "definitely",      hint: "Without any doubt",                      sentence: "I will definitely be at your performance tonight." },
    { word: "demonstrate",     hint: "Show how something works",               sentence: "The teacher will demonstrate the science experiment first." },
    { word: "determination",   hint: "Firmly decided; persistence",            sentence: "With determination, he practiced every day until he won." },
    { word: "exaggerate",      hint: "Make something seem bigger than it is",  sentence: "Don't exaggerate — it wasn't that scary!" },
    { word: "fascinate",       hint: "Hold someone's interest strongly",       sentence: "The documentary about oceans never failed to fascinate me." },
    { word: "knowledge",       hint: "Facts and understanding gained",         sentence: "Reading builds knowledge that stays with you forever." },
    { word: "punctuation",     hint: "Marks used in writing like commas",      sentence: "Correct punctuation makes your writing much easier to read." },
    { word: "significant",     hint: "Important or meaningful",                sentence: "The discovery was a significant moment in science." },
    { word: "transparent",     hint: "Able to be seen through; open",          sentence: "Good leaders are transparent about their decisions." },
    { word: "absolutely",      hint: "With no qualification, restriction",     sentence: "I am absolutely sure we locked the door." },
    { word: "academic",        hint: "Relating to education and scholarship",  sentence: "The school offers many academic programs." },
    { word: "accepting",       hint: "Consenting to receive or undertake",     sentence: "He was accepting of their apology." },
    { word: "accidental",      hint: "Happening by chance",                    sentence: "The spill on the carpet was completely accidental." },
    { word: "accomplish",      hint: "Achieve or complete successfully",       sentence: "You can accomplish anything if you work hard." },
    { word: "actually",        hint: "As the truth or facts of a situation",   sentence: "I thought it was raining, but actually it wasn't." },
    { word: "additional",      hint: "Added, extra, or supplementary",         sentence: "We will need additional chairs for our guests." },
    { word: "address",         hint: "The particulars of where someone lives", sentence: "Can you give me your mailing address?" },
    { word: "advertise",       hint: "Describe or draw attention to a product",sentence: "They plan to advertise the new game on television." },
    { word: "altogether",      hint: "Completely; totally",                    sentence: "I stopped eating candy altogether." },
    { word: "ambassador",      hint: "An accredited diplomat sent by a country",sentence: "The ambassador represented her nation with honor." },
    { word: "analysis",        hint: "Detailed examination of the parts",      sentence: "The scientist presented his analysis of the data." },
    { word: "analyze",         hint: "Discover or reveal through detailed exam",sentence: "We must analyze the results before deciding." },
    { word: "apparent",        hint: "Clearly visible or understood",          sentence: "It was apparent that he was feeling much better." },
    { word: "appreciate",      hint: "Recognize the full worth of",            sentence: "I appreciate all the help you've given me." },
    { word: "appropriate",     hint: "Suitable or proper in the circumstances",sentence: "Is this dress appropriate for a wedding?" },
    { word: "architecture",    hint: "The art or practice of designing buildings", sentence: "The ancient architecture of the city is beautiful." },
    { word: "boundary",        hint: "A line that marks the limits of an area",sentence: "The river forms a boundary between the two states." },
    { word: "brilliant",       hint: "Exceptionally clever or talented",       sentence: "Albert Einstein was a brilliant scientist." },
    { word: "briefly",         hint: "For a short time",                       sentence: "We stopped briefly to rest on our hike." },
    { word: "calculate",       hint: "Determine the amount or number",         sentence: "Can you calculate the total cost of the items?" },
    { word: "campaign",        hint: "An organized course of action",          sentence: "The campaign to clean up the park was a success." },
    { word: "capacity",        hint: "The maximum amount that something can contain", sentence: "The stadium was filled to capacity." },
    { word: "category",        hint: "A class or division of people or things",sentence: "What category does this book belong in?" },
    { word: "challenge",       hint: "A call to take part in a contest",       sentence: "The math puzzle was a fun challenge." },
    { word: "character",       hint: "The mental and moral qualities of an individual", sentence: "She has such a strong character and kind heart." },
    { word: "collection",      hint: "The action or process of collecting someone or something", sentence: "He showed us his amazing coin collection." },
    { word: "combination",     hint: "A joining or merging of different parts",sentence: "The safe required a secret combination to open." },
    { word: "commercial",      hint: "Concerned with or engaged in commerce",  sentence: "We watched a funny commercial on television." },
    { word: "committee",       hint: "A group of people appointed for a specific function", sentence: "The committee meets every Tuesday to discuss school events." },
    { word: "compete",         hint: "Strive for superiority against another",   sentence: "She will compete in the science fair this year." },
    { word: "complex",         hint: "Made up of many different parts",          sentence: "The puzzle was complex but fun to solve." },
    { word: "conclusion",      hint: "The end or final decision",                sentence: "At the conclusion of the story, everyone was happy." },
    { word: "confident",       hint: "Feeling sure about oneself",               sentence: "He was confident before stepping onto the stage." },
    { word: "constitution",    hint: "The fundamental laws of a country",        sentence: "The Constitution protects the rights of every citizen." },
    { word: "continuous",      hint: "Without interruption; unbroken",           sentence: "The rain was continuous for three days straight." },
    { word: "contribution",    hint: "Something given to help a cause",          sentence: "Her contribution to the project was invaluable." },
    { word: "controversial",   hint: "Causing discussion and disagreement",      sentence: "The decision to change the dress code was controversial." },
    { word: "convenient",      hint: "Fitting in well with needs; handy",        sentence: "The store is very convenient — it is right next door." },
    { word: "correspond",      hint: "Communicate by exchanging letters",        sentence: "They began to correspond after meeting at camp." },
    { word: "courageous",      hint: "Not deterred by danger; brave",            sentence: "The courageous firefighter ran into the burning building." },
    { word: "cyclone",         hint: "A massive rotating storm",                 sentence: "The cyclone caused terrible destruction along the coast." },
    { word: "decision",        hint: "A choice made after thought",              sentence: "Making good decisions requires thinking carefully." },
    { word: "declaration",     hint: "A formal or explicit announcement",        sentence: "The Declaration of Independence was signed in 1776." },
    { word: "decrease",        hint: "Make or become smaller in size",           sentence: "Exercise can decrease your risk of heart disease." },
    { word: "deliberate",      hint: "Done on purpose; intentional",             sentence: "Her deliberate choice to be kind changed the whole team." },
    { word: "delivery",        hint: "The action of delivering letters or goods",sentence: "The delivery arrived early in the morning." },
    { word: "democratic",      hint: "Relating to democracy or supporting it",   sentence: "Our school has a democratic student government." },
    { word: "dependent",       hint: "Relying on another for support",           sentence: "Young children are dependent on their parents." },
    { word: "depression",      hint: "Severe sadness; also an economic downturn",sentence: "Talking to a counselor helped him work through depression." },
    { word: "design",          hint: "A plan showing how something will be made",sentence: "She created a colorful design for the school mural." },
    { word: "desperate",       hint: "Feeling a hopeless desire",                sentence: "He made a desperate attempt to catch the last train." },
    { word: "difference",      hint: "A point of dissimilarity",                 sentence: "What is the difference between a frog and a toad?" },
    { word: "dimension",       hint: "A measurable extent of a space",           sentence: "A cube has three dimensions: length, width, and height." },
    { word: "diplomat",        hint: "A representative of a country abroad",     sentence: "The diplomat negotiated the peace treaty." },
    { word: "disaster",        hint: "A sudden accident causing great damage",   sentence: "The tornado was a complete disaster for the small town." },
    { word: "discipline",      hint: "Training to obey rules",                   sentence: "Athletic discipline helped her become a champion." },
    { word: "disorder",        hint: "A disruption of systematic arrangement",   sentence: "The storm left the city in complete disorder." },
    { word: "distribute",      hint: "Give out shares of something",             sentence: "The teacher distributed books to the whole class." },
    { word: "dominate",        hint: "Have power and influence over others",     sentence: "The team tended to dominate every game this season." },
    { word: "dramatic",        hint: "Sudden and striking in effect",            sentence: "The performance was a dramatic success." },
    { word: "durable",         hint: "Able to withstand wear and tear",          sentence: "These boots are extremely durable — they last for years." },
    { word: "dynamic",         hint: "Full of energy and change",                sentence: "The young teacher had a dynamic and exciting style." },
    { word: "economic",        hint: "Relating to the economy",                  sentence: "The country faced a serious economic challenge." },
    { word: "editorial",       hint: "A newspaper article giving an opinion",    sentence: "The editorial called for an end to the forest clear-cutting." },
    { word: "effective",       hint: "Producing the desired result",             sentence: "Hard work is the most effective path to success." },
    { word: "elaborate",       hint: "Involving many parts; detailed",           sentence: "She gave an elaborate explanation of her science project." },
    { word: "emotional",       hint: "Relating to feelings",                     sentence: "The farewell speech was emotional for everyone." },
    { word: "emphasis",        hint: "Special importance given to something",    sentence: "The coach placed emphasis on teamwork above all else." },
    { word: "enormous",        hint: "Very large in size or extent",             sentence: "The whale was an enormous and magnificent creature." },
    { word: "equality",        hint: "The state of being equal in rights",       sentence: "She fought her whole life for equality." },
    { word: "evolution",       hint: "The gradual development of something",     sentence: "The evolution of smartphones changed how we communicate." },
    { word: "exception",       hint: "A person or thing that is excluded",       sentence: "There is an exception to every rule." },
    { word: "expedition",      hint: "A journey for a specific purpose",         sentence: "They packed supplies for the mountain expedition." },
    { word: "experiment",      hint: "A scientific test under controlled conditions", sentence: "We ran an experiment to test how plants grow." },
    { word: "explanation",     hint: "A statement that makes something clear",   sentence: "The explanation made the math problem finally click." },
    { word: "expression",      hint: "The process of conveying feelings",        sentence: "Art is a powerful form of self-expression." },
    { word: "extraordinary",   hint: "Unusual or remarkable",                    sentence: "The acrobat's performance was truly extraordinary." },
    { word: "formation",       hint: "The action of forming or being formed",    sentence: "The marching band performed in a diamond formation." },
    { word: "frustration",     hint: "The feeling of being upset or annoyed",    sentence: "She felt great frustration when the puzzle kept falling apart." },
  ],
};
export default grade5;
