export const GRADE_3_CURRICULUM = [
  { day:1, isTestDay:false, newSkills:["multiplication_1_digit"], teachingScript:"Welcome to Grade 3 Math! Today we start multiplication — one of the most useful things you'll ever learn. Multiplication is just fast adding. 3 times 4 means 3 groups of 4, which equals 12.", teachingVisual:"3 × 4 = 12" },
  { day:2, isTestDay:false, newSkills:["multiplication_1_digit"], teachingScript:"Let's continue building our multiplication facts. Focus on your 2s, 5s, and 10s first — they are the easiest to remember!", teachingVisual:"5 × 6 = 30" },
  { day:3, isTestDay:false, newSkills:["division_basic"], teachingScript:"Division is the opposite of multiplication. If 3 times 4 is 12, then 12 divided by 3 is 4. They are a family!", teachingVisual:"12 ÷ 3 = 4" },
  { day:4, isTestDay:false, newSkills:["addition_3_digit","subtraction_3_digit"], teachingScript:"Today we tackle three-digit numbers! Adding and subtracting hundreds, tens, and ones. Line everything up carefully.", teachingVisual:"243 + 351 = 594" },
  { day:5, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:6, isTestDay:false, newSkills:["multiplication_1_digit"], teachingScript:"Let's drill our middle multiplication facts — the 6s, 7s, and 8s. These take more practice. Repetition is the key!", teachingVisual:"7 × 8 = 56" },
  { day:7, isTestDay:false, newSkills:["division_basic"], teachingScript:"Division practice with slightly bigger numbers today. Always ask yourself: how many groups of this number fit inside the big number?", teachingVisual:"45 ÷ 9 = 5" },
  { day:8, isTestDay:false, newSkills:["subtraction_3_digit"], teachingScript:"Three-digit subtraction with borrowing. When the top digit is too small, borrow from the column to the left.", teachingVisual:"502 - 248 = 254" },
  { day:9, isTestDay:false, newSkills:[], teachingScript:"Mixed review — multiplication, division, and 3-digit operations. Let's sharpen our accuracy before the big test!", teachingVisual:"Review Day" },
  { day:10, isTestDay:true, newSkills:[], teachingScript:null, teachingVisual:null },
  { day:11, isTestDay:false, newSkills:["multiplication_1_digit", "division_basic"], teachingScript:"Welcome to the next level! Today we mix multiplication and division. Remember, they are a fact family. If 4x3=12, then 12/3=4.", teachingVisual:"Fact Families" },
  { day:12, isTestDay:false, newSkills:["addition_3_digit", "subtraction_3_digit"], teachingScript:"Back to the big numbers! Adding and subtracting in the hundreds requires very neat columns. Keep your math organized.", teachingVisual:"356 + 189 = 545" },
  { day:13, isTestDay:false, newSkills:["multiplication_1_digit"], teachingScript:"Let's conquer the 9s! A fun trick for the 9s: the digits of the answer usually add up to 9. (9x2=18, 1+8=9!)", teachingVisual:"9 × 4 = 36" },
  { day:14, isTestDay:false, newSkills:["division_basic"], teachingScript:"More division. Take a big pile, split it into equal groups. Practice makes it automatic.", teachingVisual:"56 ÷ 8 = 7" },
  { day:15, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:16, isTestDay:false, newSkills:["subtraction_3_digit", "multiplication_1_digit"], teachingScript:"A real brain workout today. We are switching from heavy borrowing in subtraction to rapid multiplication.", teachingVisual:"Stay Sharp!" },
  { day:17, isTestDay:false, newSkills:["addition_3_digit", "division_basic"], teachingScript:"Mixing 3-digit addition with basic division. Keep your facts quick and your columns straight.", teachingVisual:"Math Flexibility" },
  { day:18, isTestDay:false, newSkills:["multiplication_1_digit", "division_basic"], teachingScript:"Full drill on fact families today. multiplication and division are two sides of the same coin.", teachingVisual:"4 × 5 = 20 | 20 ÷ 5 = 4" },
  { day:19, isTestDay:false, newSkills:[], teachingScript:"Practice day. Take a deep breath and apply your mastery to these review problems.", teachingVisual:"Review Day" },
  { day:20, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:21, isTestDay:false, newSkills:["addition_3_digit"], teachingScript:"Strictly 3-digit addition today. Let's practice carrying over into the hundreds and thousands.", teachingVisual:"899 + 215 = 1114" },
  { day:22, isTestDay:false, newSkills:["subtraction_3_digit"], teachingScript:"Strictly 3-digit subtraction. Borrowing across a zero is the hardest part. You must borrow from the hundreds first!", teachingVisual:"503 - 279 = 224" },
  { day:23, isTestDay:false, newSkills:["multiplication_1_digit"], teachingScript:"Let's make sure our 7s, 8s, and 9s are totally memorized. Flashcard speed!", teachingVisual:"8 × 9 = 72" },
  { day:24, isTestDay:false, newSkills:["division_basic", "subtraction_3_digit"], teachingScript:"Division paired with borrowing subtraction. Read the signs carefully before leaping in.", teachingVisual:"Look before you leap" },
  { day:25, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:26, isTestDay:false, newSkills:["multiplication_1_digit", "addition_3_digit"], teachingScript:"The home stretch! Large addition and quick multiplication. You're doing amazing.", teachingVisual:"Almost there!" },
  { day:27, isTestDay:false, newSkills:["division_basic", "multiplication_1_digit"], teachingScript:"Rapid fire fact families up to the 10s. Try to beat your record.", teachingVisual:"Speed Math" },
  { day:28, isTestDay:false, newSkills:["addition_3_digit", "subtraction_3_digit"], teachingScript:"Our final day of new drills on 3-digit column math.", teachingVisual:"Organized Columns" },
  { day:29, isTestDay:false, newSkills:[], teachingScript:"The ultimate review day! Practice everything you have learned this month.", teachingVisual:"Mega Review" },
  { day:30, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null }
];
