export const GRADE_11_CURRICULUM = [
  { day:1, isTestDay:false, newSkills:["trig_sin_cos"], teachingScript:"Welcome to Pre-Calculus! We begin with Trigonometry. The unit circle is a circle with radius 1. Sine is the y-coordinate, Cosine is the x-coordinate.", teachingVisual:"sin(90°) = 1" },
  { day:2, isTestDay:false, newSkills:["exponential_solve"], teachingScript:"Exponential solving is about finding the unknown power. If 3 to the power of x is 9, x is 2.", teachingVisual:"2^x = 8 -> x = 3" },
  { day:3, isTestDay:false, newSkills:["trig_sin_cos", "exponential_solve"], teachingScript:"Mixing trig values and exponents. These are transcendental functions.", teachingVisual:"Transcendental Math" },
  { day:4, isTestDay:false, newSkills:["logarithm_basic"], teachingScript:"Logarithms are the inverse of exponents! log base 2 of 8 asks: what power of 2 is 8?", teachingVisual:"log_2(8) = 3" },
  { day:5, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:6, isTestDay:false, newSkills:["exponential_solve", "logarithm_basic"], teachingScript:"Logs and exponents go hand in hand. They cancel each other out.", teachingVisual:"Logs & Exponents" },
  { day:7, isTestDay:false, newSkills:["rational_solve"], teachingScript:"Solving rational equations involves clearing the denominator. Multiply both sides by x.", teachingVisual:"10 / x = 2 -> x = 5" },
  { day:8, isTestDay:false, newSkills:["trig_sin_cos", "rational_solve"], teachingScript:"Mixed pre-calc concepts. Keep your unit circle memorized.", teachingVisual:"Unit Circle Mastery" },
  { day:9, isTestDay:false, newSkills:[], teachingScript:"Practice day. Look over your formulas carefully before testing.", teachingVisual:"Review Day" },
  { day:10, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:11, isTestDay:false, newSkills:["trig_sin_cos", "logarithm_basic"], teachingScript:"Welcome to the next level! Today we mix trigonometry and logarithm logic.", teachingVisual:"Trig & Logs" },
  { day:12, isTestDay:false, newSkills:["exponential_solve", "rational_solve"], teachingScript:"Calculating complex x values.", teachingVisual:"Isolating X" },
  { day:13, isTestDay:false, newSkills:["trig_sin_cos", "exponential_solve"], teachingScript:"Heavy advanced algebra mix! Think logically.", teachingVisual:"Pre-Calc Mix" },
  { day:14, isTestDay:false, newSkills:["logarithm_basic", "rational_solve"], teachingScript:"Strictly rational logic today.", teachingVisual:"Rational Rules" },
  { day:15, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:16, isTestDay:false, newSkills:["trig_sin_cos"], teachingScript:"Strictly trig equations.", teachingVisual:"SOH CAH TOA" },
  { day:17, isTestDay:false, newSkills:["logarithm_basic"], teachingScript:"Solving strictly for missing exponents.", teachingVisual:"Power Rules" },
  { day:18, isTestDay:false, newSkills:["exponential_solve", "trig_sin_cos"], teachingScript:"Drilling the core components of late high school math.", teachingVisual:"Math Readiness" },
  { day:19, isTestDay:false, newSkills:[], teachingScript:"Practice day. Look over your formulas carefully before testing.", teachingVisual:"Review Day" },
  { day:20, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:21, isTestDay:false, newSkills:["rational_solve", "exponential_solve"], teachingScript:"Strictly finding dimensions. Remember: Base times Height.", teachingVisual:"B x H" },
  { day:22, isTestDay:false, newSkills:["trig_sin_cos"], teachingScript:"Advanced relationships.", teachingVisual:"Relationships" },
  { day:23, isTestDay:false, newSkills:["logarithm_basic", "trig_sin_cos"], teachingScript:"Mix up the concepts to build mental agility.", teachingVisual:"Mental Agility" },
  { day:24, isTestDay:false, newSkills:["rational_solve", "logarithm_basic"], teachingScript:"Math drills. Stay accurate, write clearly.", teachingVisual:"Neat writing" },
  { day:25, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:26, isTestDay:false, newSkills:["trig_sin_cos", "exponential_solve"], teachingScript:"Home stretch! You are mastering pre-calculus.", teachingVisual:"Push through" },
  { day:27, isTestDay:false, newSkills:["rational_solve", "logarithm_basic"], teachingScript:"Simple but precise computational mixing.", teachingVisual:"Precise math" },
  { day:28, isTestDay:false, newSkills:["trig_sin_cos", "exponential_solve", "rational_solve"], teachingScript:"Our final day of new drills on PreCalc.", teachingVisual:"You got this!" },
  { day:29, isTestDay:false, newSkills:[], teachingScript:"The ultimate review day! Practice everything you have learned this month.", teachingVisual:"Mega Review" },
  { day:30, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null }
];
