export const GRADE_8_CURRICULUM = [
  { day:1, isTestDay:false, newSkills:["algebra_2_step"], teachingScript:"Welcome to Grade 8 Math! Today we solve two-step equations. You must undo the operations in reverse order. For 2x plus 3 equals 11, first subtract 3 to get 2x equals 8, then divide by 2 to get x equals 4.", teachingVisual:"2x + 3 = 11  →  x = 4" },
  { day:2, isTestDay:false, newSkills:["exponents_basic"], teachingScript:"Exponents! Two to the third power means 2 times 2 times 2, which equals 8. The exponent tells you how many times to multiply the base by itself.", teachingVisual:"2³ = 2×2×2 = 8" },
  { day:3, isTestDay:false, newSkills:["square_roots"], teachingScript:"Square roots undo exponents. The square root of 49 asks: what number times itself equals 49? The answer is 7, because 7 times 7 is 49.", teachingVisual:"√49 = 7" },
  { day:4, isTestDay:false, newSkills:["pythagorean_theorem"], teachingScript:"The Pythagorean Theorem! For any right triangle, a squared plus b squared equals c squared, where c is the longest side, called the hypotenuse. If a is 3 and b is 4, then c is 5!", teachingVisual:"3² + 4² = 5²  (9+16=25)" },
  { day:5, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:6, isTestDay:false, newSkills:["algebra_2_step"], teachingScript:"More two-step equations — this time with subtraction and division steps. Remember to work backwards from the equal sign.", teachingVisual:"3x - 7 = 14  →  x = 7" },
  { day:7, isTestDay:false, newSkills:["exponents_basic","square_roots"], teachingScript:"Exponents and square roots together. These are inverse operations — square roots undo squaring, and squaring undoes square roots.", teachingVisual:"√25 = 5  →  5² = 25" },
  { day:8, isTestDay:false, newSkills:["pythagorean_theorem"], teachingScript:"More Pythagorean Theorem practice with different triangles. Always identify which side is c first — it's always the longest side, across from the right angle.", teachingVisual:"5² + 12² = 13²" },
  { day:9, isTestDay:false, newSkills:[], teachingScript:"Full review — two-step algebra, exponents, square roots, and Pythagorean Theorem before the test!", teachingVisual:"Review Day" },
  { day:10, isTestDay:true, newSkills:[], teachingScript:null, teachingVisual:null },
  { day:11, isTestDay:false, newSkills:["algebra_2_step", "exponents_basic"], teachingScript:"Welcome to the next level! Mixing 2-step algebra and calculating basic exponents. Remember that exponents are just repeated multiplication.", teachingVisual:"3² = 9" },
  { day:12, isTestDay:false, newSkills:["square_roots", "pythagorean_theorem"], teachingScript:"Pythagorean Theorem runs entirely on squares and square roots. Today we practice finding the perfect square root to solve the triangle.", teachingVisual:"√144 = 12" },
  { day:13, isTestDay:false, newSkills:["algebra_2_step", "pythagorean_theorem"], teachingScript:"Heavy algebra and geometry mix! Think logically.", teachingVisual:"Geometry + Algebra" },
  { day:14, isTestDay:false, newSkills:["exponents_basic", "square_roots"], teachingScript:"Square numbers and their roots are inverses. If you memorize perfect squares up to 12, this is easy.", teachingVisual:"10² = 100, √100 = 10" },
  { day:15, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:16, isTestDay:false, newSkills:["algebra_2_step"], teachingScript:"Strictly 2-step algebra. Isolate the variable by doing reverse order of operations.", teachingVisual:"Reverse PEMDAS" },
  { day:17, isTestDay:false, newSkills:["pythagorean_theorem"], teachingScript:"Solving strictly for missing hypotenuses today.", teachingVisual:"a² + b² = c²" },
  { day:18, isTestDay:false, newSkills:["exponents_basic", "square_roots", "algebra_2_step"], teachingScript:"Drilling the core components of high school math readiness.", teachingVisual:"Math Readiness" },
  { day:19, isTestDay:false, newSkills:[], teachingScript:"Practice day. Look over your formulas carefully before testing.", teachingVisual:"Review Day" },
  { day:20, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:21, isTestDay:false, newSkills:["exponents_basic"], teachingScript:"Strictly exponential growth. Watch how fast exponents make numbers grow.", teachingVisual:"Exponential Growth" },
  { day:22, isTestDay:false, newSkills:["square_roots"], teachingScript:"Estimating square roots. If a number is between perfect squares, its root is a decimal.", teachingVisual:"√50 is ~ 7.1" },
  { day:23, isTestDay:false, newSkills:["pythagorean_theorem", "algebra_2_step"], teachingScript:"Mix up the concepts to build mental agility.", teachingVisual:"Mental Agility" },
  { day:24, isTestDay:false, newSkills:["algebra_2_step", "exponents_basic"], teachingScript:"Math drills. Stay accurate, write clearly.", teachingVisual:"Neat writing" },
  { day:25, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:26, isTestDay:false, newSkills:["pythagorean_theorem", "square_roots"], teachingScript:"Home stretch! You are mastering pre-high school operations.", teachingVisual:"Push through" },
  { day:27, isTestDay:false, newSkills:["algebra_2_step", "square_roots"], teachingScript:"Simple but precise computational mixing.", teachingVisual:"Precise math" },
  { day:28, isTestDay:false, newSkills:["algebra_2_step", "exponents_basic", "pythagorean_theorem"], teachingScript:"Our final day of new drills on Algebra and Roots.", teachingVisual:"You got this!" },
  { day:29, isTestDay:false, newSkills:[], teachingScript:"The ultimate review day! Practice everything you have learned this month.", teachingVisual:"Mega Review" },
  { day:30, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null }
];
