export const GRADE_6_CURRICULUM = [
  { day:1, isTestDay:false, newSkills:["integers_addition"], teachingScript:"Welcome to Grade 6 Math! Today we enter the world of integers — positive and negative numbers. Think of a number line. Adding negative seven to positive three lands you at negative four.", teachingVisual:"3 + (-7) = -4" },
  { day:2, isTestDay:false, newSkills:["integers_subtraction"], teachingScript:"Subtracting integers has a rule: subtracting a negative is the same as adding a positive! Five minus negative three equals five plus three, which is eight.", teachingVisual:"5 - (-3) = 8" },
  { day:3, isTestDay:false, newSkills:["order_of_operations"], teachingScript:"Order of operations — Please Excuse My Dear Aunt Sally — Parentheses, Exponents, Multiply and Divide, then Add and Subtract. Always follow this order!", teachingVisual:"3 + 4 × 2 = 11" },
  { day:4, isTestDay:false, newSkills:["ratio_simplify"], teachingScript:"Ratios compare two quantities. The ratio 6 to 9 simplifies to 2 to 3 by dividing both by 3. We treat it just like simplifying fractions.", teachingVisual:"6:9 → 2:3" },
  { day:5, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:6, isTestDay:false, newSkills:["integers_addition","integers_subtraction"], teachingScript:"Mixed integer drill today — some addition, some subtraction. Watch your signs carefully!", teachingVisual:"-8 + 5 = -3" },
  { day:7, isTestDay:false, newSkills:["order_of_operations"], teachingScript:"More complex order of operations with multiple steps. Write out each step and check your work as you go.", teachingVisual:"(2+3) × 4 - 1 = 19" },
  { day:8, isTestDay:false, newSkills:["ratio_simplify"], teachingScript:"Applying ratios to real-world problems. If there are 4 boys for every 6 girls, that ratio simplifies to 2 to 3.", teachingVisual:"12:18 → 2:3" },
  { day:9, isTestDay:false, newSkills:[], teachingScript:"Full review of integers, order of operations, and ratios. Prepare for the test!", teachingVisual:"Review Day" },
  { day:10, isTestDay:true, newSkills:[], teachingScript:null, teachingVisual:null },
  { day:11, isTestDay:false, newSkills:["integers_addition", "integers_subtraction"], teachingScript:"Welcome to the next level! Today we mix integer addition and subtraction. A negative minus a positive is just moving further left on the number line.", teachingVisual:"-4 - (+3) = -7" },
  { day:12, isTestDay:false, newSkills:["order_of_operations", "ratio_simplify"], teachingScript:"Calculate the expression first, then simplify the final ratio.", teachingVisual:"Order of Operations" },
  { day:13, isTestDay:false, newSkills:["ratio_simplify", "integers_addition"], teachingScript:"Mixing ratios and integers. Keep your rules separate in your mind.", teachingVisual:"Isolate the rules" },
  { day:14, isTestDay:false, newSkills:["integers_subtraction", "order_of_operations"], teachingScript:"Order of operations with heavy negative numbers today. Parentheses go first!", teachingVisual:"PEMDAS" },
  { day:15, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:16, isTestDay:false, newSkills:["ratio_simplify"], teachingScript:"Strictly ratios today. Find the greatest common factor and divide both sides by it.", teachingVisual:"GCF" },
  { day:17, isTestDay:false, newSkills:["integers_addition", "integers_subtraction"], teachingScript:"Rapid fire integer operations. Positive and negative rules must be automatic.", teachingVisual:"Number Line Visuals" },
  { day:18, isTestDay:false, newSkills:["order_of_operations", "ratio_simplify"], teachingScript:"Complex calculations today. Take your time and write out every single step.", teachingVisual:"Write Your Steps" },
  { day:19, isTestDay:false, newSkills:[], teachingScript:"Practice day. Look over your integer rules before the test.", teachingVisual:"Review Day" },
  { day:20, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:21, isTestDay:false, newSkills:["order_of_operations"], teachingScript:"Strictly complex equations today. This prepares you for Pre-Algebra.", teachingVisual:"Math Logic" },
  { day:22, isTestDay:false, newSkills:["integers_subtraction"], teachingScript:"Subtracting negative numbers. Remember: minus a negative equals a PLUS.", teachingVisual:"- (-x) = +x" },
  { day:23, isTestDay:false, newSkills:["ratio_simplify", "integers_addition"], teachingScript:"Mix up the concepts to build mental agility.", teachingVisual:"Mental Agility" },
  { day:24, isTestDay:false, newSkills:["integers_subtraction", "order_of_operations"], teachingScript:"Math drills. Stay accurate, write clearly.", teachingVisual:"Neat writing" },
  { day:25, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:26, isTestDay:false, newSkills:["ratio_simplify", "order_of_operations"], teachingScript:"Home stretch! You are mastering upper middle school concepts.", teachingVisual:"Push through" },
  { day:27, isTestDay:false, newSkills:["integers_addition", "integers_subtraction"], teachingScript:"Simple but precise computational mixing.", teachingVisual:"Precise math" },
  { day:28, isTestDay:false, newSkills:["integers_subtraction", "order_of_operations", "ratio_simplify"], teachingScript:"Our final day of new drills on integers and operations.", teachingVisual:"You got this!" },
  { day:29, isTestDay:false, newSkills:[], teachingScript:"The ultimate review day! Practice everything you have learned this month.", teachingVisual:"Mega Review" },
  { day:30, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null }
];
