export const GRADE_7_CURRICULUM = [
  { day:1, isTestDay:false, newSkills:["pre_algebra_1_step"], teachingScript:"Welcome to Grade 7 Math — Algebra begins! An equation has an unknown, called x. Your job is to find x by doing the opposite operation on both sides. If x plus 5 equals 9, subtract 5 from both sides to get x equals 4.", teachingVisual:"x + 5 = 9  →  x = 4" },
  { day:2, isTestDay:false, newSkills:["pre_algebra_multiply"], teachingScript:"Solving equations with multiplication. If 3x equals 12, divide both sides by 3 to isolate x. x equals 4.", teachingVisual:"3x = 12  →  x = 4" },
  { day:3, isTestDay:false, newSkills:["integers_multiplication"], teachingScript:"Multiplying integers! The sign rules are simple: positive times positive equals positive. Negative times negative equals positive. Different signs give you negative.", teachingVisual:"-4 × 3 = -12" },
  { day:4, isTestDay:false, newSkills:["pre_algebra_1_step","pre_algebra_multiply"], teachingScript:"Mixed pre-algebra practice — some additive equations, some multiplicative. Stay organized and always check your answer by plugging x back in.", teachingVisual:"5x = 35  →  x = 7" },
  { day:5, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:6, isTestDay:false, newSkills:["pre_algebra_1_step"], teachingScript:"Subtraction equations today. If x minus 4 equals 11, add 4 to both sides. x equals 15.", teachingVisual:"x - 4 = 11  →  x = 15" },
  { day:7, isTestDay:false, newSkills:["integers_multiplication"], teachingScript:"More integer multiplication — review and push into harder combinations.", teachingVisual:"-7 × -8 = 56" },
  { day:8, isTestDay:false, newSkills:["pre_algebra_multiply"], teachingScript:"Division equations. If x over 4 equals 3, multiply both sides by 4. x equals 12.", teachingVisual:"x/4 = 3  →  x = 12" },
  { day:9, isTestDay:false, newSkills:[], teachingScript:"Pre-algebra and integer full review. Get ready for the test!", teachingVisual:"Review Day" },
  { day:10, isTestDay:true, newSkills:[], teachingScript:null, teachingVisual:null },
  { day:11, isTestDay:false, newSkills:["pre_algebra_1_step", "pre_algebra_multiply"], teachingScript:"Welcome to the next level! Today we mix addition/subtraction algebra with multiplication/division algebra. Always isolate X.", teachingVisual:"Isolate X" },
  { day:12, isTestDay:false, newSkills:["integers_multiplication"], teachingScript:"Deep dive into multiplying integers. Multiply normally, then check: same signs = positive, different signs = negative.", teachingVisual:"Sign Rules" },
  { day:13, isTestDay:false, newSkills:["pre_algebra_1_step", "integers_multiplication"], teachingScript:"Mixing basic algebra paths. Remember that subtracting a negative is adding a positive.", teachingVisual:"Watch the signs" },
  { day:14, isTestDay:false, newSkills:["pre_algebra_multiply", "integers_multiplication"], teachingScript:"Multiplying algebra pieces. If -3x = 12, then x = -4. Divide by exactly what is next to X.", teachingVisual:"Divide by coefficient" },
  { day:15, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:16, isTestDay:false, newSkills:["pre_algebra_1_step"], teachingScript:"Strictly 1-step equations today. Do the opposite operation to both sides.", teachingVisual:"Both Sides" },
  { day:17, isTestDay:false, newSkills:["integers_multiplication", "pre_algebra_multiply"], teachingScript:"Fast percentage checks and decimal sums. Mental math wins here.", teachingVisual:"Mental Math" },
  { day:18, isTestDay:false, newSkills:["pre_algebra_1_step", "pre_algebra_multiply"], teachingScript:"Don't confuse the rules! Additive opposite vs multiplicative inverse.", teachingVisual:"Know the Rules" },
  { day:19, isTestDay:false, newSkills:[], teachingScript:"Practice day. Look over your algebraic rules.", teachingVisual:"Review Day" },
  { day:20, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:21, isTestDay:false, newSkills:["integers_multiplication"], teachingScript:"Strictly negative and positive multiplication. Build your speed.", teachingVisual:"Speed Round" },
  { day:22, isTestDay:false, newSkills:["pre_algebra_multiply"], teachingScript:"Watch out for fractional equations. If x/3 = 5, multiply both sides by 3.", teachingVisual:"Clear the fraction" },
  { day:23, isTestDay:false, newSkills:["pre_algebra_1_step", "integers_multiplication"], teachingScript:"Mix equations and integers. Foundation for higher algebra.", teachingVisual:"Foundation" },
  { day:24, isTestDay:false, newSkills:["pre_algebra_multiply", "pre_algebra_1_step"], teachingScript:"Math drills. Stay accurate, write clearly.", teachingVisual:"Neat writing" },
  { day:25, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:26, isTestDay:false, newSkills:["pre_algebra_1_step", "integers_multiplication"], teachingScript:"Home stretch! You are mastering Pre-Algebra rapidly.", teachingVisual:"Push through" },
  { day:27, isTestDay:false, newSkills:["pre_algebra_multiply", "pre_algebra_1_step"], teachingScript:"Simple but precise computational mixing.", teachingVisual:"Precise math" },
  { day:28, isTestDay:false, newSkills:["pre_algebra_1_step", "pre_algebra_multiply", "integers_multiplication"], teachingScript:"Our final day of new drills on Pre-algebra.", teachingVisual:"You got this!" },
  { day:29, isTestDay:false, newSkills:[], teachingScript:"The ultimate review day! Practice everything you have learned this month.", teachingVisual:"Mega Review" },
  { day:30, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null }
];
