export const GRADE_12_CURRICULUM = [
  { day:1, isTestDay:false, newSkills:["derivative_power_rule"], teachingScript:"Welcome to Calculus! The derivative is the rate of change. Use the power rule: multiply by the exponent, then drop the exponent by 1.", teachingVisual:"d/dx x² = 2x" },
  { day:2, isTestDay:false, newSkills:["integral_polynomial"], teachingScript:"Integration is the opposite of derivation. It finds the area under a curve. Increase the exponent by 1 and divide.", teachingVisual:"∫ x dx = ½x²" },
  { day:3, isTestDay:false, newSkills:["derivative_power_rule", "integral_polynomial"], teachingScript:"Mixing derivatives and integrals! The fundamental theorem of calculus connects them.", teachingVisual:"Fundamental Theorem" },
  { day:4, isTestDay:false, newSkills:["probability_dice"], teachingScript:"Let's shift to Statistics. Probability is the number of desired outcomes divided by total outcomes.", teachingVisual:"P(Heads) = 50%" },
  { day:5, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:6, isTestDay:false, newSkills:["mean_average", "probability_dice"], teachingScript:"Mean is the average. Add them all up and divide by how many there are.", teachingVisual:"Sum / Count" },
  { day:7, isTestDay:false, newSkills:["derivative_power_rule", "mean_average"], teachingScript:"Solving applied calculus and stats problems.", teachingVisual:"Calculus & Stats" },
  { day:8, isTestDay:false, newSkills:["integral_polynomial", "mean_average"], teachingScript:"Mixed high level concepts. Keep your logic straight.", teachingVisual:"Logic Mastery" },
  { day:9, isTestDay:false, newSkills:[], teachingScript:"Practice day. Look over your formulas carefully before testing.", teachingVisual:"Review Day" },
  { day:10, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:11, isTestDay:false, newSkills:["derivative_power_rule", "probability_dice"], teachingScript:"Welcome to the next level! Today we mix calculus derivatives and probability.", teachingVisual:"Calc & Stats" },
  { day:12, isTestDay:false, newSkills:["integral_polynomial", "mean_average"], teachingScript:"Calculating accumulation and averages. They are totally related!", teachingVisual:"Integrals are accumulation" },
  { day:13, isTestDay:false, newSkills:["derivative_power_rule", "integral_polynomial"], teachingScript:"Heavy calculus mix! Think logically.", teachingVisual:"Calculus Mix" },
  { day:14, isTestDay:false, newSkills:["probability_dice", "mean_average"], teachingScript:"Strictly statistics logic today.", teachingVisual:"Stats Rules" },
  { day:15, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:16, isTestDay:false, newSkills:["derivative_power_rule"], teachingScript:"Strictly derivatives today.", teachingVisual:"Power Rule" },
  { day:17, isTestDay:false, newSkills:["probability_dice"], teachingScript:"Solving strictly for probability.", teachingVisual:"Chance" },
  { day:18, isTestDay:false, newSkills:["integral_polynomial", "derivative_power_rule"], teachingScript:"Drilling the core components of college math readiness.", teachingVisual:"Math Readiness" },
  { day:19, isTestDay:false, newSkills:[], teachingScript:"Practice day. Look over your formulas carefully before testing.", teachingVisual:"Review Day" },
  { day:20, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:21, isTestDay:false, newSkills:["mean_average", "integral_polynomial"], teachingScript:"Strictly finding dimensions. Remember: Base times Height.", teachingVisual:"B x H" },
  { day:22, isTestDay:false, newSkills:["derivative_power_rule"], teachingScript:"Advanced linear relationships. Negative slopes go DOWN.", teachingVisual:"Negative Slopes" },
  { day:23, isTestDay:false, newSkills:["probability_dice", "derivative_power_rule"], teachingScript:"Mix up the concepts to build mental agility.", teachingVisual:"Mental Agility" },
  { day:24, isTestDay:false, newSkills:["mean_average", "probability_dice"], teachingScript:"Math drills. Stay accurate, write clearly.", teachingVisual:"Neat writing" },
  { day:25, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:26, isTestDay:false, newSkills:["derivative_power_rule", "integral_polynomial"], teachingScript:"Home stretch! You are mastering Calculus.", teachingVisual:"Push through" },
  { day:27, isTestDay:false, newSkills:["mean_average", "probability_dice"], teachingScript:"Simple but precise computational mixing.", teachingVisual:"Precise math" },
  { day:28, isTestDay:false, newSkills:["derivative_power_rule", "integral_polynomial", "mean_average"], teachingScript:"Our final day of new drills on Calculus.", teachingVisual:"You got this!" },
  { day:29, isTestDay:false, newSkills:[], teachingScript:"The ultimate review day! Practice everything you have learned this month.", teachingVisual:"Mega Review" },
  { day:30, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null }
];
