export const GRADE_2_CURRICULUM = [
  { day:1, isTestDay:false, newSkills:["addition_2_digit","skip_count_2"], teachingScript:"Welcome to Grade 2 Math! Today we learn to add two-digit numbers like 23 plus 41. We also practice counting by 2s — a great speed trick!", teachingVisual:"23 + 41 = 64" },
  { day:2, isTestDay:false, newSkills:["subtraction_2_digit"], teachingScript:"Today we subtract two-digit numbers. Start with the ones column, then the tens column. Remember to borrow when needed!", teachingVisual:"75 - 32 = 43" },
  { day:3, isTestDay:false, newSkills:["skip_count_5","skip_count_10"], teachingScript:"Counting by 5s and 10s is like a superpower for speed math! 5, 10, 15, 20... 10, 20, 30, 40... Let's master these patterns.", teachingVisual:"35 + 5 = 40" },
  { day:4, isTestDay:false, newSkills:["even_odd"], teachingScript:"Even numbers can be split perfectly in half. Odd ones cannot. 2, 4, 6, 8 are even. 1, 3, 5, 7, 9 are odd. Let's identify them together!", teachingVisual:"6 = EVEN  |  7 = ODD" },
  { day:5, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:6, isTestDay:false, newSkills:["addition_2_digit"], teachingScript:"More two-digit addition practice today with bigger numbers. Remember to line up your ones and tens columns carefully.", teachingVisual:"56 + 37 = 93" },
  { day:7, isTestDay:false, newSkills:["subtraction_2_digit"], teachingScript:"Let's practice subtraction with borrowing. When the top digit is smaller than the bottom, borrow 10 from the tens column!", teachingVisual:"81 - 47 = 34" },
  { day:8, isTestDay:false, newSkills:["skip_count_10"], teachingScript:"Today we count by 10s from different starting numbers, not just from zero. 14, 24, 34, 44... Try it!", teachingVisual:"37 + 10 = 47" },
  { day:9, isTestDay:false, newSkills:[], teachingScript:"Review day! Let's practice everything we've learned so far — skip counting, two-digit addition, and subtraction.", teachingVisual:"Practice & Review" },
  { day:10, isTestDay:true, newSkills:[], teachingScript:null, teachingVisual:null },
  { day:11, isTestDay:false, newSkills:["addition_2_digit", "subtraction_2_digit"], teachingScript:"Welcome to the next level! Today we mix 2-digit addition and subtraction. Always check the sign before you start carrying or borrowing!", teachingVisual:"Mixed 2-Digit Math" },
  { day:12, isTestDay:false, newSkills:["skip_count_2", "even_odd"], teachingScript:"Did you know that skip counting by 2s only lands on EVEN numbers? Try it: 2, 4, 6, 8, 10! It's a great mathematical connection.", teachingVisual:"2, 4, 6 = EVEN" },
  { day:13, isTestDay:false, newSkills:["skip_count_5", "addition_2_digit"], teachingScript:"Skip counting by 5s is useful for reading analog clocks! Practice your 5s, then do some 2-digit adding.", teachingVisual:"5, 10, 15, 20..." },
  { day:14, isTestDay:false, newSkills:["subtraction_2_digit", "skip_count_10"], teachingScript:"Subtracting big numbers takes focus. Don't forget to count by 10s as a quick break!", teachingVisual:"95 - 47 = ?" },
  { day:15, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:16, isTestDay:false, newSkills:["even_odd", "addition_2_digit"], teachingScript:"Let's identify more even and odd numbers. A trick: you only have to look at the LAST digit to know if a huge number is even or odd!", teachingVisual:"342 -> 2 is EVEN" },
  { day:17, isTestDay:false, newSkills:["skip_count_2", "skip_count_5"], teachingScript:"Skip counting day! Going back and forth from 2s to 5s forces your brain to switch gears and get stronger.", teachingVisual:"Fast Counting" },
  { day:18, isTestDay:false, newSkills:["subtraction_2_digit", "even_odd"], teachingScript:"Borrowing heavily today! If the bottom number is bigger than the top number in the ones column, borrow tens!", teachingVisual:"Tens & Ones" },
  { day:19, isTestDay:false, newSkills:[], teachingScript:"Practice day. Look over your addition and subtraction forms carefully before the test.", teachingVisual:"Review Day" },
  { day:20, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:21, isTestDay:false, newSkills:["addition_2_digit"], teachingScript:"Let's push for speed and accuracy in our 2-digit addition.", teachingVisual:"67 + 25 = 92" },
  { day:22, isTestDay:false, newSkills:["subtraction_2_digit"], teachingScript:"Strictly subtraction today. You have to master borrowing to move to 3-digit numbers soon.", teachingVisual:"84 - 19 = 65" },
  { day:23, isTestDay:false, newSkills:["skip_count_2", "skip_count_5", "skip_count_10"], teachingScript:"The ultimate skip counting challenge! 2s, 5s, and 10s all mixed up.", teachingVisual:"Mental Math Agility" },
  { day:24, isTestDay:false, newSkills:["even_odd", "addition_2_digit"], teachingScript:"Even/odd recognition combined with addition. A solid foundation for Grade 3 math.", teachingVisual:"Math Logic" },
  { day:25, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:26, isTestDay:false, newSkills:["subtraction_2_digit", "skip_count_2"], teachingScript:"We're on the home stretch! Heavy subtraction paired with rapid counting.", teachingVisual:"Focus!" },
  { day:27, isTestDay:false, newSkills:["addition_2_digit", "subtraction_2_digit"], teachingScript:"Total mix of 2-digit addition and subtraction. Don't let the signs trick you.", teachingVisual:"Check the Sign" },
  { day:28, isTestDay:false, newSkills:["even_odd", "skip_count_5", "skip_count_10"], teachingScript:"Our final day of drills on patterns and odds/evens.", teachingVisual:"Pattern Mastery" },
  { day:29, isTestDay:false, newSkills:[], teachingScript:"The ultimate review day! Practice everything you have learned this month.", teachingVisual:"Mega Review" },
  { day:30, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null }
];
