export const GRADE_K_CURRICULUM = [
  { day:1, isTestDay:false, newSkills:["number_recognition"], teachingScript:"Welcome to Math! Let's learn our numbers. Numbers show us how many things we have.", teachingVisual:"1, 2, 3, 4, 5!" },
  { day:2, isTestDay:false, newSkills:["counting_up_to_5"], teachingScript:"Let's learn how to count in order. Point to each thing as you count: 1, 2, 3!", teachingVisual:"Count: 1, 2, 3" },
  { day:3, isTestDay:false, newSkills:["number_recognition", "counting_up_to_5"], teachingScript:"Counting and seeing numbers together! Keep practicing those counting skills.", teachingVisual:"Numbers are everywhere" },
  { day:4, isTestDay:false, newSkills:["counting_up_to_10"], teachingScript:"We are getting higher! Let's count all the way up to 10. You have 10 fingers!", teachingVisual:"6, 7, 8, 9, 10" },
  { day:5, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:6, isTestDay:false, newSkills:["number_recognition", "counting_up_to_10"], teachingScript:"Look at big numbers! Look at the symbols and recognize them instantly.", teachingVisual:"Recognizing Numbers" },
  { day:7, isTestDay:false, newSkills:["counting_up_to_5", "counting_up_to_10"], teachingScript:"Mixed counting! Some small, some big.", teachingVisual:"Count them up!" },
  { day:8, isTestDay:false, newSkills:["number_recognition", "counting_up_to_5"], teachingScript:"Numbers are fun! Reviewing everything.", teachingVisual:"Fun with Math" },
  { day:9, isTestDay:false, newSkills:[], teachingScript:"Practice day. Look at your numbers before the test.", teachingVisual:"Review Day" },
  { day:10, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:11, isTestDay:false, newSkills:["counting_up_to_10", "number_recognition"], teachingScript:"Welcome to the next level! Today we mix counting high and identifying numbers.", teachingVisual:"Mixing it up" },
  { day:12, isTestDay:false, newSkills:["counting_up_to_5", "counting_up_to_10"], teachingScript:"Counting fast! Say the next number.", teachingVisual:"Say it fast" },
  { day:13, isTestDay:false, newSkills:["number_recognition", "counting_up_to_10"], teachingScript:"Heavy numbers mix! Think logically.", teachingVisual:"Logic time" },
  { day:14, isTestDay:false, newSkills:["counting_up_to_5", "number_recognition"], teachingScript:"Strictly small logic today. Easy stuff.", teachingVisual:"Easy Math" },
  { day:15, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:16, isTestDay:false, newSkills:["counting_up_to_10"], teachingScript:"Strictly big counting today.", teachingVisual:"Big Count" },
  { day:17, isTestDay:false, newSkills:["number_recognition"], teachingScript:"Solving strictly for missing numbers.", teachingVisual:"What number?" },
  { day:18, isTestDay:false, newSkills:["counting_up_to_5", "counting_up_to_10"], teachingScript:"Drilling the core components of early math readiness.", teachingVisual:"Math Readiness" },
  { day:19, isTestDay:false, newSkills:[], teachingScript:"Practice day. Look over your formulas carefully before testing.", teachingVisual:"Review Day" },
  { day:20, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:21, isTestDay:false, newSkills:["counting_up_to_10", "number_recognition"], teachingScript:"Strictly finding dimensions. Base times Height.", teachingVisual:"B x H" },
  { day:22, isTestDay:false, newSkills:["counting_up_to_5"], teachingScript:"Advanced linear relationships. Negative slopes go DOWN.", teachingVisual:"Negative Slopes" },
  { day:23, isTestDay:false, newSkills:["number_recognition", "counting_up_to_10"], teachingScript:"Mix up the concepts to build mental agility.", teachingVisual:"Mental Agility" },
  { day:24, isTestDay:false, newSkills:["counting_up_to_5", "number_recognition"], teachingScript:"Math drills. Stay accurate, write clearly.", teachingVisual:"Neat writing" },
  { day:25, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:26, isTestDay:false, newSkills:["counting_up_to_10", "counting_up_to_5"], teachingScript:"Home stretch! You are mastering algebra and geometry.", teachingVisual:"Push through" },
  { day:27, isTestDay:false, newSkills:["number_recognition", "counting_up_to_5"], teachingScript:"Simple but precise computational mixing.", teachingVisual:"Precise math" },
  { day:28, isTestDay:false, newSkills:["counting_up_to_10", "number_recognition", "counting_up_to_5"], teachingScript:"Our final day of new drills on Algebra and Geometry.", teachingVisual:"You got this!" },
  { day:29, isTestDay:false, newSkills:[], teachingScript:"The ultimate review day! Practice everything you have learned this month.", teachingVisual:"Mega Review" },
  { day:30, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null }
];
