export const GRADE_4_CURRICULUM = [
  { day:1, isTestDay:false, newSkills:["multiplication_2_digit"], teachingScript:"Welcome to Grade 4 Math! Today we multiply two-digit numbers by single digits using the standard algorithm. Break the problem into parts: ones first, then tens.", teachingVisual:"23 × 4 = 92" },
  { day:2, isTestDay:false, newSkills:["long_division"], teachingScript:"Long division! This is where you divide big numbers step by step. Divide, Multiply, Subtract, Bring down — D.M.S.B is your secret code.", teachingVisual:"84 ÷ 4 = 21" },
  { day:3, isTestDay:false, newSkills:["fraction_addition_like_denom"], teachingScript:"Fractions with the same bottom number are easy to add! Three-eighths plus two-eighths equals five-eighths. Just add the top numbers and keep the bottom the same.", teachingVisual:"3/8 + 2/8 = 5/8" },
  { day:4, isTestDay:false, newSkills:["fraction_simplify"], teachingScript:"Simplifying fractions means making them as small as possible. 4 over 8 is the same as 1 over 2. Divide both top and bottom by the same number.", teachingVisual:"4/8 = 1/2" },
  { day:5, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:6, isTestDay:false, newSkills:["multiplication_2_digit"], teachingScript:"Two-digit times two-digit multiplication today! Break it into partial products and then add them together.", teachingVisual:"13 × 12 = 156" },
  { day:7, isTestDay:false, newSkills:["long_division"], teachingScript:"Let's practice longer division problems with remainders. When a number doesn't divide evenly, that leftover is called the remainder.", teachingVisual:"29 ÷ 4 = 7 R1" },
  { day:8, isTestDay:false, newSkills:["fraction_addition_like_denom","fraction_simplify"], teachingScript:"Adding fractions and simplifying the result — the full pipeline! Add the tops, keep the bottom, then simplify if you can.", teachingVisual:"6/10 → 3/5" },
  { day:9, isTestDay:false, newSkills:[], teachingScript:"Full review day — long division, 2-digit multiplication, and fractions. Sharpen your pencil for tomorrow!", teachingVisual:"Review Day" },
  { day:10, isTestDay:true, newSkills:[], teachingScript:null, teachingVisual:null },
  { day:11, isTestDay:false, newSkills:["multiplication_2_digit", "long_division"], teachingScript:"Welcome to the next level! Today we mix multiplication and division. Keep your scratch paper neat so you don't lose your numbers.", teachingVisual:"Multiply & Divide" },
  { day:12, isTestDay:false, newSkills:["fraction_addition_like_denom", "fraction_simplify"], teachingScript:"Fraction addition, but today you MUST simplify every answer. 6 over 8 is not done until it becomes 3 over 4.", teachingVisual:"6/8 -> 3/4" },
  { day:13, isTestDay:false, newSkills:["long_division", "fraction_simplify"], teachingScript:"Division paired with simplifying. We are training your brain to see numbers as flexible pieces.", teachingVisual:"Flex your Math" },
  { day:14, isTestDay:false, newSkills:["multiplication_2_digit", "fraction_addition_like_denom"], teachingScript:"Big multiplication and fraction addition. Always remember: keep the denominator the exact same when adding.", teachingVisual:"Keep the bottom" },
  { day:15, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:16, isTestDay:false, newSkills:["long_division"], teachingScript:"Strictly long division today. Take your time. Divide, multiply, subtract, bring down.", teachingVisual:"D M S B" },
  { day:17, isTestDay:false, newSkills:["fraction_simplify", "fraction_addition_like_denom"], teachingScript:"Heavy focus on fractions. Always look for the greatest common factor when simplifying.", teachingVisual:"Greatest Common Factor" },
  { day:18, isTestDay:false, newSkills:["multiplication_2_digit", "long_division"], teachingScript:"Full computational practice. You've got this.", teachingVisual:"Calculate!" },
  { day:19, isTestDay:false, newSkills:[], teachingScript:"Review day. Double check your multiplication tables.", teachingVisual:"Review Day" },
  { day:20, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:21, isTestDay:false, newSkills:["multiplication_2_digit"], teachingScript:"Let's push for speed and accuracy in 2-digit multiplication.", teachingVisual:"24 × 51 = 1224" },
  { day:22, isTestDay:false, newSkills:["long_division"], teachingScript:"More division. Try to predict the remainder before you finish.", teachingVisual:"Mental Division" },
  { day:23, isTestDay:false, newSkills:["fraction_addition_like_denom", "fraction_simplify"], teachingScript:"Fast fractions. Make sure you don't accidentally add the bottom numbers!", teachingVisual:"Don't Add Bottoms!" },
  { day:24, isTestDay:false, newSkills:["multiplication_2_digit", "long_division"], teachingScript:"The algorithms should feel like second nature by now.", teachingVisual:"Math Muscle Memory" },
  { day:25, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:26, isTestDay:false, newSkills:["fraction_simplify", "long_division"], teachingScript:"A healthy mix of number manipulation. Stay sharp.", teachingVisual:"Stay Sharp!" },
  { day:27, isTestDay:false, newSkills:["fraction_addition_like_denom", "multiplication_2_digit"], teachingScript:"Add fractions, multiply digits, keep moving.", teachingVisual:"Keep Moving" },
  { day:28, isTestDay:false, newSkills:["multiplication_2_digit", "long_division", "fraction_simplify"], teachingScript:"Our final day of new drills on Grade 4 skills.", teachingVisual:"Algorithm Mastery" },
  { day:29, isTestDay:false, newSkills:[], teachingScript:"The ultimate review day! Practice everything you have learned this month.", teachingVisual:"Mega Review" },
  { day:30, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null }
];
