export const GRADE_5_CURRICULUM = [
  { day:1, isTestDay:false, newSkills:["fraction_subtraction_like_denom"], teachingScript:"Grade 5 Math starts with fraction subtraction. Just like addition, keep the denominator and subtract the numerators. Five eighths minus two eighths equals three eighths.", teachingVisual:"5/8 - 2/8 = 3/8" },
  { day:2, isTestDay:false, newSkills:["fraction_multiplication"], teachingScript:"Multiplying fractions is actually simpler than adding! Just multiply across — top times top, bottom times bottom. Two thirds times three fourths equals six twelfths.", teachingVisual:"2/3 × 3/4 = 6/12" },
  { day:3, isTestDay:false, newSkills:["decimal_addition"], teachingScript:"Decimals are fractions wearing disguise! When adding decimals, line up the decimal points and add just like whole numbers.", teachingVisual:"3.45 + 1.20 = 4.65" },
  { day:4, isTestDay:false, newSkills:["percent_of_number"], teachingScript:"Percents are parts out of 100. To find 10% of a number, just move the decimal point one place to the left. 10% of 80 is 8.", teachingVisual:"25% of 80 = 20" },
  { day:5, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:6, isTestDay:false, newSkills:["fraction_multiplication"], teachingScript:"More fraction multiplication practice! After multiplying, always check if you can simplify the answer by dividing top and bottom by a common number.", teachingVisual:"3/5 × 5/6 = 15/30 = 1/2" },
  { day:7, isTestDay:false, newSkills:["decimal_addition"], teachingScript:"Decimal subtraction practice — same rule as addition, just line up those decimal points and subtract carefully.", teachingVisual:"7.50 - 3.25 = 4.25" },
  { day:8, isTestDay:false, newSkills:["percent_of_number"], teachingScript:"Finding 25% and 50% of numbers today. Remember: 50% is just dividing by 2. 25% is dividing by 4.", teachingVisual:"50% of 60 = 30" },
  { day:9, isTestDay:false, newSkills:[], teachingScript:"Review day! Fractions, decimals, and percents — the three cousins of the same idea.", teachingVisual:"Review Day" },
  { day:10, isTestDay:true, newSkills:[], teachingScript:null, teachingVisual:null },
  { day:11, isTestDay:false, newSkills:["fraction_subtraction_like_denom", "fraction_multiplication"], teachingScript:"Welcome to the next level! Today we mix subtracting and multiplying fractions. Remember formatting: subtraction requires common denominators, multiplication does NOT.", teachingVisual:"Rules of fractions" },
  { day:12, isTestDay:false, newSkills:["decimal_addition", "percent_of_number"], teachingScript:"Decimals and percents mix perfectly. 50% is half, 25% is a quarter.", teachingVisual:"50% = 0.5" },
  { day:13, isTestDay:false, newSkills:["fraction_multiplication", "percent_of_number"], teachingScript:"Multiplying fractions and calculating percents. Both are about finding a 'piece' of a whole.", teachingVisual:"Find the Piece" },
  { day:14, isTestDay:false, newSkills:["fraction_subtraction_like_denom", "decimal_addition"], teachingScript:"Simple subtractions and decimal line-ups.", teachingVisual:"Line up the decimals!" },
  { day:15, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:16, isTestDay:false, newSkills:["fraction_multiplication"], teachingScript:"Strictly fraction multiplication today. Remember to multiply across, then simplify if possible.", teachingVisual:"Top x Top | Bottom x Bottom" },
  { day:17, isTestDay:false, newSkills:["percent_of_number", "decimal_addition"], teachingScript:"Fast percentage checks and decimal sums. Mental math wins here.", teachingVisual:"Mental Math" },
  { day:18, isTestDay:false, newSkills:["fraction_subtraction_like_denom", "fraction_multiplication"], teachingScript:"Don't confuse the rules! Cross multiply vs common bottoms.", teachingVisual:"Know the Rules" },
  { day:19, isTestDay:false, newSkills:[], teachingScript:"Practice day. Look over your percentage shortcuts.", teachingVisual:"Review Day" },
  { day:20, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:21, isTestDay:false, newSkills:["percent_of_number"], teachingScript:"Strictly percentages today! Find 10%, 25%, and 50% quickly.", teachingVisual:"10%, 25%, 50%" },
  { day:22, isTestDay:false, newSkills:["decimal_addition"], teachingScript:"Watch out for jagged decimal additions. Add zeros to the end if you need placeholders.", teachingVisual:"1.5 + 2.45 -> 1.50 + 2.45" },
  { day:23, isTestDay:false, newSkills:["fraction_multiplication", "decimal_addition"], teachingScript:"Mix decimals and fractions. Two different ways to write pieces of a whole.", teachingVisual:"Parts of a whole" },
  { day:24, isTestDay:false, newSkills:["fraction_subtraction_like_denom", "percent_of_number"], teachingScript:"Math drills. Stay accurate, write clearly.", teachingVisual:"Neat writing" },
  { day:25, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null },
  { day:26, isTestDay:false, newSkills:["percent_of_number", "fraction_multiplication"], teachingScript:"Home stretch! You are mastering upper elementary math concepts rapidly.", teachingVisual:"Push through" },
  { day:27, isTestDay:false, newSkills:["decimal_addition", "fraction_subtraction_like_denom"], teachingScript:"Simple but precise computational mixing.", teachingVisual:"Precise math" },
  { day:28, isTestDay:false, newSkills:["fraction_subtraction_like_denom", "fraction_multiplication", "percent_of_number"], teachingScript:"Our final day of new drills on fractions and percents.", teachingVisual:"You got this!" },
  { day:29, isTestDay:false, newSkills:[], teachingScript:"The ultimate review day! Practice everything you have learned this month.", teachingVisual:"Mega Review" },
  { day:30, isTestDay:true,  newSkills:[], teachingScript:null, teachingVisual:null }
];
